### ISSUE TITLE
GLMakie not working successful build but failed tests

### ISSUE THREAD

**Issue by MatisPatel** [MakieOrg/Makie.jl#1267]
I get warnings from tests about AbstractPlotting being moved to Makie. Clean install and build in new environment (Windows 10, OpenGL 4.6)

```
Window handling: Error During Test at C:\Users\defen\.julia\packages\GLMakie\rcy
kA\test\unit_tests.jl:10
  Got exception outside of a @test
  MethodError: Cannot `convert` an object of type Vector{Char} to an object of t
ype Char
```

and 

```
Pick a plot element or plot elements inside a rectangle: Error During Test at C:
\Users\defen\.julia\packages\GLMakie\rcykA\test\unit_tests.jl:27
  Got exception outside of a @test
  MethodError: Cannot `convert` an object of type Vector{Char} to an object of t
ype Char
```

summary of failed tests 
```
Test Summary:                                             | Pass  Error  Total
unit tests                                                |    1      2      3
  Window handling                                         |    1      1      2
  Pick a plot element or plot elements inside a rectangle |           1      1
```

**Comment by ximonsson** [comment]
i had the same error yesterday (but on linux), and it was because an older version of `GLMakie.jl` was being installed (`AbstractPlotting` is deprecated). this seemed to be because the lastest version would not be installed next to `Plotly`. I removed `Plotly`, updated, and then everything worked.

i can't see what version you have installed,  but if you do not have `v0.4.6`, and you are gettng `v0.2.something` instead,  it could be because you have added `Plotly` to your project. Try removing it and update.

Best of luck

**Comment by ffreyer** [comment]
If you see AbstractPlotting you're way behind the current Makie version at this point. You can check what's holding you back by checking the Project.toml in the repo https://github.com/MakieOrg/Makie.jl/blob/master/Project.toml for the current version and trying `]add Makie@<version>`
