### ISSUE TITLE
WGLMakie Resize Feature

### ISSUE THREAD

**Issue by bradcarman** [MakieOrg/Makie.jl#1318]
I was wondering if it would be possible to auto-resize a WGLMakie figure?  For example, when the figure is displayed in a VSCode Plot Pane window, would it be possible to:

1. Fill the plot pane window based on the window initial size
2. Auto-resize the figure based on a change to the plot pane size?  

Basically, I'm looking for similar functionality as the PlotlyJS.jl package, which fills and resizes based on the Blink window or the VSCode Plot Pane size.

**Comment by bardo84** [comment]
Hi,
>PlotlyJS.jl package, which fills and resizes based on the Blink window or the VSCode Plot Pane size.

Does not work for me. 

```
using Plots
plotlyjs()
display(plot(sign.(randn(100, 4)), layout = (4, 1), link =:x))
```

Can you show a basic example?

**Comment by bradcarman** [comment]
`Plots` has a [bug](https://github.com/JuliaPlots/Plots.jl/issues/1074), you need to use PlotlyJS instead...

![plotlyjs](https://user-images.githubusercontent.com/40798837/135625129-4bae9f87-9992-4193-b203-4ca0900385ee.gif)

**Comment by bardo84** [comment]
Thanks a lot @bradcarman !
Another reason to convert to Makie. Feels low-level with lots of controls. I am writing a linked subplots function. Not that difficult. The examples from the doc  are clumsy at times. Need more convenience routines or a Plots.jl integration.
Are you aware of a collection of Makie receipes where one could contribute?

But now back to have the resize in Makie!

**Comment by lazarusA** [comment]
Looking for this as well. Any hints?

**Comment by robsmith11** [comment]
I'd also like a way to make the plot fullscreen in my browser.  I tried playing around with JSServe.jl and exporting the plot to a html file, but didn't see any obvious to change the dimensions.

**Comment by SimonDanisch** [comment]
This is somehow more difficult than it should be! But it's definitely on the wish list!

**Comment by SimonDanisch** [comment]
This has been implemented by:
`WGLMakie.activate!(resize_to=:parent)`
`WGLMakie.activate!(resize_to=:body)`

**Comment by sprig** [comment]
This does not work correctly, often. In particular, the base case of just displaying a scatter plot in an unmodified default bonito output, only fills half the screen (with resize to parent)

**Comment by SimonDanisch** [comment]
Do you have an MWE?

**Comment by sprig** [comment]
```
julia> using WGLMakie

julia> WGLMakie.activate!(resize_to=:parent)

julia> scatter(rand(10))
```

Opens a scatter plot, that does not fill the entire window.

**Comment by SimonDanisch** [comment]
This simply doesn't have a full screen parent... That's what  `resize_to=:body`  is for - in case you have nothing but the plot on the page and want to make it full screen.

**Comment by sprig** [comment]
I thought I replied earlier but i guess i skipped submitting. I see. In that case i find the flag name “body”+docs to be a bit confusing.

Anyway, this means that unless use make their own resizers, the only suitable mode for workflows /other/ than one-figure-at-time is to use :parent.

However, with :parent if I wrap my figure in an observable (eg to be able to regenerate dynamically in response to some input), additional containers are inserted in the dom between the figure and the container of the observable, usually more than one and in a nonlinear fashion.

Worse, those containers are unclassed and some of them are spans , which makes for layout hell for me as i need to cargo cult some css from SO/LLM that usually doesn’t work, wasting a lot of time.

Perhaps Im using it wrong? I would happily accept a different approach for generating figures dynamically in cases where it is inconvenient to “simply update the data” compared to regenerating from scratch.

One alternative i can see is watching the figure observable and regenerating the app entirely when the observable changes but that would refresh the page and reset all interactions, wouldn’t it? And, wouldn’t that defeat the purpose of being able to insert observables into the dom in the first place?

alternatively, i can probably manage my resizer in js but, it feels a bit redundant. perhaps allow resizing to a given parent container id/class rather than just immediate parent? That would seem fairly robust and simple.

Ideally I think observables would have a maximum of one container inserted into the dom correlating to the observable container itself, and with a named class for users to modify. But that might be hard to implement. I tried modifying the jsrender methods for observables and managed to get some of the way there, but i still wasnt able to get rid of all unclassed containers added in the tree due to the observable wrapper…

**Comment by sprig** [comment]
So, I have tinkered around a bit and one solution that seems to work so far. It is to wrap the entire returned DOM in an observable inside of which the outermost content forcibly takes over the entire window, and avoid including other observables directly into the page, ie without type wrappers with custom jsrender methods. Then update the DOM observable whenever any dynamic component changes (ones which I would otherwise wrap in an observable). \

Seems to cause a refresh/redraw of the page but it might be reasonable it a large component changes. I'll also need to see how this interacts with other controls on the page.
