### ISSUE TITLE
allow colormap for stroke in poly

### ISSUE THREAD

**Issue by lazarusA** [MakieOrg/Makie.jl#1432]
At the moment, doing 

`poly(polys; color=:transparent,, strokewidth = 0.5, strokecolor = 1:n)`

outputs polygons with different colours, it takes by default the viridis colormap. However, doing 

`poly(polys; color=:transparent,, strokewidth = 0.5, strokecolor = to_colormap(:plasma,n))`

for a different colormap (just for lines) it doesn't work. I looked at the source code, but I'm not sure where/or how this change should be done.

**Comment by ffreyer** [comment]
The general design for colormaps is:
- `colormap` defines what colors are used
- `colorrange` sets the minimum and maximum values corresponding to the first and last color in the colormap
- `lowclip` is the color for anything below the minimum value
- `highclip` is the color for anything above the maximum
- `nan_color` is the color for any value that is nan (maybe also missing?)
- `color` is the value used to fetch a color

So you'd need to pass `colormap = ...` and probably some reasonable values as `color = ...` to lines/linesegments if `strokecolor` is a colormap. That "if `strokecolor` is a colormap" is going to be a problem since vectors of colors are accepted as a `color` and as a `colormap`.

**Comment by lazarusA** [comment]
as I said, doing `strokecolor = 1:n` gives different colours (from viridis) for different polygons. Then, probably it will be best to have an extra argument for a different colormap for lines/linesegments. Like `strokecolormap = ...`, this is actually what I was thinking, but again I don't see where to make the appropriate change to the recipe as it is. 

The other was just a suggestion, just in case it could be easier.

**Comment by ffreyer** [comment]
For `strokecolormap` you'd need to add it as an attribute in the recipe macro
https://github.com/JuliaPlots/Makie.jl/blob/befc016aa974ad06b178e02e3d29f0b751558f54/src/basic_recipes/poly.jl#L21-L41
and pass it as `colormap = plot.strokecolormap` in the plot-calls
https://github.com/JuliaPlots/Makie.jl/blob/befc016aa974ad06b178e02e3d29f0b751558f54/src/basic_recipes/poly.jl#L59-L64
https://github.com/JuliaPlots/Makie.jl/blob/befc016aa974ad06b178e02e3d29f0b751558f54/src/basic_recipes/poly.jl#L128-L132

**Comment by ffreyer** [comment]
closed by #3145
