### ISSUE TITLE
Error bars scale with x-axis scaling

### ISSUE THREAD

**Issue by Klafyvel** [MakieOrg/Makie.jl#1455]
When using `errorbars` with `whiskerwidth` ≠ 0 on an axis with `scale=log10`, the whiskers scale with the axis.

```julia
using CairoMakie

f = Figure()
ax = Axis(f[1,1], xscale=log10)

xs = [1, 1/10, 1/100]
ys = randn(3)
δys = randn(3) .* 0.1

errorbars!(ax, xs, ys, δys, whiskerwidth = 3)

f
```

![image](https://user-images.githubusercontent.com/6209071/142390867-cc1640b7-a913-4ca4-9b9e-cd6057ba81d9.png)

Edit : package version

```julia
  [13f3f980] CairoMakie v0.6.6
```

**Comment by KronosTheLate** [comment]
I came here to raise the same issue:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/61620837/170044593-00d4a454-5806-417a-80f0-de22eae9b3ec.png">

Also, the value of whiskerwidth in my plot is 10_000. Perhaps it could be possible to set the whiskerwidth in terms of pixels, for non-identity scaling?

**Comment by jkrumbiegel** [comment]
It is supposed to be in screen units, it's just that I forgot to include scene transformations at the time. But now that we have space settings it should be easier to do this anyway. Right now it's implemented by projecting once into screen space and then back into data space because at the time there was only data space to use.

**Comment by ffreyer** [comment]
This was part of my motivation for #1730. Even with that it'll be annoying though, since whiskers are centered at a data space position with a pixel width and thickness. It might actually be easier/better to implement it with scatter for GLMakie. (I.e. make a specialized line character, center-aligned and scaled with a `Vec2f(width, height)`)

**Comment by chelate** [comment]
Had this problem with boxplots as well....

I know this may be an unpopular opinion, but I believe one should be able to change the axis labels to log space and then transform the input functions as one pleases. It's much easier to manipulate things this way without worrying about yet another coordinate. A broadcasted log10.(y) is much more readable than another keyword.

**Comment by KronosTheLate** [comment]
You could also make the xlabel something like log(x), or manually set the xticks by passing (i believe it is) a touple og vectors, the first with the linear ticks and the second with the derired display strings. Otherwise, I personally really like not having to transform the data, and have it happen automatically to match the actual axis scale.

**Comment by Klafyvel** [comment]
Amazing, thanks.
