### ISSUE TITLE
I want to contribute (open for suggestions)

### ISSUE THREAD

**Issue by kimkroener** [MakieOrg/Makie.jl#1566]
Hi everyone, 

I'm a Masters's student at the University of Stuttgart and participating in the course [Simulation Software Engineering](https://simulation-software-engineering.github.io/homepage/). As part of this course we are asked to contribute to an open source project to get familiar with the development workflow of such projects.  For this challenge I chose Makie and I'm looking for suggestions :) 

The contribution should be small but meaningful and there are no limitations for this contribution. It could be a new tutorial, bug fix, documentation, or any other maintenance task. However it should be something that is a good first issue as I'm a beginner Julia (and Makie) user (I do have programming experience in Matlab and Python) and I'm looking forward to learn by contributing.

**Comment by ffreyer** [comment]
One suggestion I have is working on patterns/hatching. A probably very simple thing you could fix is that the [show method](https://github.com/JuliaPlots/Makie.jl/blob/c453051af7e1cccdf63b8465f4d805b0cdebabab/src/patterns.jl#L11) for `Makie.ImagePattern` errors.
Currently patterns are only supported by `mesh` plots in GLMakie and are therefore still an unofficial feature. I think the most important step towards officially supporting patterns is a CairoMakie implementation. This means figuring out how Cairo handles hatching, adjusting `LinePattern` to be compatible with it and adding it to the [CairoMakie mesh method](https://github.com/JuliaPlots/Makie.jl/blob/c453051af7e1cccdf63b8465f4d805b0cdebabab/CairoMakie/src/primitives.jl#L644).  (And if `LinePattern` is a terrible representation it should be fine to replace it too. There just needs to be a `to_image` method so that GLMakie know what image texture to draw.)

The original prs implementing patterns are https://github.com/JuliaPlots/AbstractPlotting.jl/pull/457 and https://github.com/JuliaPlots/GLMakie.jl/pull/108. There is also an issue requesting this: https://github.com/JuliaPlots/Makie.jl/issues/1385

**Comment by kimkroener** [comment]
Thank you for your suggestions and sorry for my late reply. Pattern support sounds super interesting. 
I started looking into it and I realized I don't feel comfortable enough with my Julia (and Makie) skills yet to work on a feature implementation. 

Instead I also took a look at documentation issues - there is for example #1112 for boxplot attributes. I think this [docstring](https://github.com/JuliaPlots/Makie.jl/blob/8146f27ffa86d70a6aba786353ddc89f4d8b136d/src/stats/boxplot.jl#L19) has been updated in part but it doesn't show  in the [API reference](https://makie.juliaplots.org/stable/documentation/api_reference/#BoxPlot) at all and does not show the current docstring when calling help from the REPL 

```julia 
help?> boxplot

```

Also for the violin, the doc string does not match the attributes implemented. Related to that is issue #1312. 

I'd like to fix these issues, is there anything I need to be aware of e.g. a style guide?

**Comment by MariusDrulea** [comment]
Maybe a bit late, but I noticed Makie is terrible in dealing with images or large arrays. Makie is awesome, but it was tested only for small data so far. See here: https://github.com/JuliaPlots/Makie.jl/issues/1427, https://github.com/JuliaPlots/Makie.jl/issues/1650. This un-optimal way of showing the images is a serious bottleneck and there is room for contributing in this direction as well.

**Comment by MariusDrulea** [comment]
@SimonDanisch I initially used image instead of heatmap because heatmap supports transparency while image does not. At that point in time I was not aware that image is a lot lighter than heatmap. 

Therefore, indeed, there is no serious bottleneck anymore.

**Comment by harisorgn** [comment]
> One suggestion I have is working on patterns/hatching. A probably very simple thing you could fix is that the [show method](https://github.com/JuliaPlots/Makie.jl/blob/c453051af7e1cccdf63b8465f4d805b0cdebabab/src/patterns.jl#L11) for `Makie.ImagePattern` errors. 

Hi there,
wanted to start contributing to Makie and Julia and thought that this would be an entry-level fix. I just created PR https://github.com/JuliaPlots/Makie.jl/pull/1794 with a basic fix to the show function (it just does not error).

**Comment by SimonDanisch** [comment]
Thank you! Closing this since its not really an "issue" :)
