### ISSUE TITLE
Having text as part of theme

### ISSUE THREAD

**Issue by Moelf** [MakieOrg/Makie.jl#1679]
https://www.google.com/search?q=atlas+plotting+style&client=firefox-b-1-d&channel=tus5&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjChbKiqIj2AhVok-AKHcH_CNEQ_AUoAXoECAEQAw&biw=1222&bih=863&dpr=1.5#imgrc=afxeDH8zVgYfxM

many science collaboration has a fixed (loosely) style for plots, many of them include a collaboration text tag. It would be nice if it can be part of a `Theme()`. The implementation probably would be similar to `text()` or `annotation()` with a relative scale and position placement

**Comment by Moelf** [comment]
should partly be improved by:
- https://github.com/JuliaPlots/Makie.jl/issues/1638

**Comment by ffreyer** [comment]
`space` allows you to place text in pixel or relative coordinates. You can also place it (or any other plot) anywhere by plotting to `fig.scene` (may require some `translate!(plot, 0, 0, 10_000)` to be on top).
I don't see this becoming something automatic, since different figures would have different "good" position for this. So I think this is about as completed as it's going to get.

Note that if we merge #4150 you'd want to do `overlay = Scene(fig.scene, viewport = fig.scene.viewport)` and plot to that instead. That would then not require any translation.
