### ISSUE TITLE
Saving continuously updated figure leads to large number of allocations

### ISSUE THREAD

**Issue by andrei-iosif** [MakieOrg/Makie.jl#1692]
In the following example (using GLMakie v0.5.3), the number of memory allocations and runtime increases at each iteration, when the figure is updated. However, if I do not save the figure, the allocations remain constant. Same behavior happens with both **image()** and **heatmap()**.

```
function simple_figure()
    fig, ax, plot_obj = image(rand(1664, 512), colorrange=(0, 1), interpolate = false)
    for i in 1:10
        x = rand(1664, 512)
        @time plot_obj[1] = x
        save("C:\\Temp\\fig_$i.jpeg", fig)
    end    
end
```

**Example with save**
```
  0.000809 seconds (25 allocations: 3.252 MiB)
  0.091658 seconds (84 allocations: 6.505 MiB, 97.71% gc time)
  0.006845 seconds (143 allocations: 9.758 MiB)
  0.003022 seconds (202 allocations: 13.011 MiB)
  0.011600 seconds (281 allocations: 16.265 MiB, 64.48% gc time)
  0.004602 seconds (320 allocations: 19.518 MiB)
  0.005716 seconds (379 allocations: 22.771 MiB)
  0.005913 seconds (438 allocations: 26.025 MiB)
  0.010164 seconds (517 allocations: 29.278 MiB, 31.96% gc time)
  0.011699 seconds (576 allocations: 32.532 MiB, 29.40% gc time)
```

**Example without save**
```
  0.000864 seconds (25 allocations: 3.252 MiB)
  0.000852 seconds (25 allocations: 3.252 MiB)
  0.000945 seconds (25 allocations: 3.252 MiB)
  0.000897 seconds (25 allocations: 3.252 MiB)
  0.000885 seconds (25 allocations: 3.252 MiB)
  0.001041 seconds (25 allocations: 3.252 MiB)
  0.001969 seconds (25 allocations: 3.252 MiB)
  0.001823 seconds (25 allocations: 3.252 MiB)
  0.002146 seconds (25 allocations: 3.252 MiB)
  0.000880 seconds (25 allocations: 3.252 MiB)
```

Also, this behavior persists when using **Observables**:
```
function simple_figure_2()
    x = Observable(rand(1664, 512))
    fig, ax, plot_obj = image(rand(1664, 512), colorrange=(0, 1), interpolate = false)
    
    for i in 1:10
        new_x = rand(1664, 512)
        @time x[] = new_x
        save("C:\\Temp\\fig_$i.png", fig)   
    end
end
```

**Comment by andrei-iosif** [comment]
I have tested the above examples using an older version of GLMakie (v.0.4.7) and the issue did not appear.

```
  0.000887 seconds (25 allocations: 3.251 MiB)
  0.001212 seconds (77 allocations: 3.270 MiB)
  0.001203 seconds (68 allocations: 3.269 MiB)
  0.001049 seconds (68 allocations: 3.269 MiB)
  0.001083 seconds (68 allocations: 3.269 MiB)
  0.001139 seconds (68 allocations: 3.269 MiB)
  0.001152 seconds (68 allocations: 3.269 MiB)
  0.001015 seconds (68 allocations: 3.269 MiB)
  0.001251 seconds (68 allocations: 3.269 MiB)
  0.001321 seconds (68 allocations: 3.269 MiB)
```

**Comment by MariusDrulea** [comment]
This issue is a **blocker** for image based AI applications and others.

I have tested this code with the current version of GLMakie, 0.6.2, and the issue still persists. Actually, it's worse, even more allocations are created. The real issue here is not the number of allocations, but the amount of time spent on saving the image to file. In the first 10 iterations _`save` takes about 0.05_ seconds. After this, _every `save` operation takes 1.85 seconds. Huge!_ Now let's do some machine learning and run such a code for a couple thousand images. 
I do also have a classical algo and the runtime is about 0.1 seconds per image, a really good runtime. Julia is awesome. Python sucks here :D. However, my efforts are runined by the `save` runtime issue.

Here is my complete code:
```
using GLMakie

function save_function()
    fig, ax, plot_obj = image(rand(1664, 512), interpolate=false)
    for i in 1:100
        println(i)        
        @time plot_obj[1] = rand(1664, 512)
        @time save("C:\\Temp\\fig_$i.png", ax.scene)
    end
end

save_function()
```

And here is the output:
```
iteration 1
  0.004393 seconds (44 allocations: 9.752 MiB)
  0.057048 seconds (4.02 k allocations: 6.855 MiB)
iteration 2
  0.006514 seconds (136 allocations: 13.007 MiB)
  0.053714 seconds (3.87 k allocations: 6.191 MiB)
iteration 3
  0.007048 seconds (228 allocations: 16.262 MiB)
  0.050923 seconds (3.75 k allocations: 5.604 MiB)
iteration 4
  0.041585 seconds (326 allocations: 19.517 MiB, 74.74% gc time)
  0.039960 seconds (3.65 k allocations: 5.086 MiB)
iteration 5
  0.008519 seconds (412 allocations: 22.772 MiB)
  0.038127 seconds (3.55 k allocations: 4.638 MiB)
iteration 6
  0.008878 seconds (504 allocations: 26.026 MiB)
  0.033436 seconds (3.48 k allocations: 4.259 MiB)
iteration 7
  0.009555 seconds (596 allocations: 29.281 MiB)
  0.031845 seconds (3.43 k allocations: 3.952 MiB)
iteration 8
  0.010605 seconds (688 allocations: 32.536 MiB)
  0.030914 seconds (3.39 k allocations: 3.716 MiB)
iteration 9
  0.012239 seconds (780 allocations: 35.791 MiB)
  0.019797 seconds (3.40 k allocations: 3.575 MiB)
iteration 10
  0.033475 seconds (884 allocations: 39.046 MiB, 57.64% gc time)
  1.852132 seconds (7.94 k allocations: 6.279 MiB)
iteration 11
  0.012079 seconds (964 allocations: 42.301 MiB)
  0.299775 seconds (7.37 k allocations: 6.251 MiB)
iteration 12
  0.015218 seconds (1.06 k allocations: 45.556 MiB)
  1.888264 seconds (7.94 k allocations: 6.265 MiB)
iteration 13
  0.014571 seconds (1.15 k allocations: 48.811 MiB)
  1.843963 seconds (7.94 k allocations: 6.265 MiB)
iteration 14
  0.031344 seconds (1.24 k allocations: 52.065 MiB, 52.97% gc time)
  1.815292 seconds (7.94 k allocations: 6.268 MiB)
iteration 15
  0.020025 seconds (1.33 k allocations: 55.320 MiB)
  1.839649 seconds (7.95 k allocations: 6.266 MiB)
iteration 16
  0.017860 seconds (1.42 k allocations: 58.575 MiB)
  1.843011 seconds (7.94 k allocations: 6.265 MiB)
iteration 17
  0.031601 seconds (1.52 k allocations: 61.830 MiB, 41.02% gc time)
  1.813150 seconds (7.94 k allocations: 6.265 MiB)
iteration 18
  0.020894 seconds (1.61 k allocations: 65.085 MiB)
  1.818426 seconds (7.95 k allocations: 6.265 MiB)
iteration 19
  0.022618 seconds (1.70 k allocations: 68.340 MiB)
  1.833656 seconds (7.95 k allocations: 6.266 MiB)
iteration 20
  0.046787 seconds (1.79 k allocations: 71.595 MiB, 32.99% gc time)
  1.843463 seconds (7.95 k allocations: 6.265 MiB)
```

**Comment by asinghvi17** [comment]
I cannot replicate this behaviour on my machine (Mac M1), on Makie v0.17.2 and GLMakie v0.6.2.

Could you try displaying your figure first like so:
```julia
using GLMakie

function save_function()
    fig, ax, plot_obj = image(rand(1664, 512), interpolate=false)
    display(fig)
    for i in 1:100
        println(i)        
        @time plot_obj[1] = rand(1664, 512)
        @time save("C:\\Temp\\fig_$i.png", ax.scene)
    end
end

save_function()
```
and see what happens?  I'm wondering whether there is some external process which causes the window to become buggy, since the update time stays approximately the same.

Also, do you see the same issue with CairoMakie (`using CairoMakie` instead of GLMakie)?

**Comment by MariusDrulea** [comment]
I'm using Windows10. 
display(fig) does not change the behaviour

With `using CairoMakie     CairoMakie.activate!()` updating the figure (`plot_obj[1] = ...`) no longer create a large number of allocations and this update seems to be fine. The save operations behave the same for all iterations: 2.56 M allocations and 0.28 seconds per save. Is this the normal behaviour?

The output when using Cairo:
```
iteration 1
  0.006472 seconds (44 allocations: 9.752 MiB)
  0.285909 seconds (2.56 M allocations: 74.758 MiB)
iteration 2
  0.043247 seconds (44 allocations: 9.752 MiB, 83.94% gc time)
  0.249496 seconds (2.56 M allocations: 74.758 MiB)
iteration 3
  0.005623 seconds (44 allocations: 9.752 MiB)
  0.268417 seconds (2.56 M allocations: 74.758 MiB)
iteration 4
  0.030960 seconds (44 allocations: 9.752 MiB, 82.01% gc time)
  0.273080 seconds (2.56 M allocations: 74.758 MiB)
iteration 5
  0.005612 seconds (44 allocations: 9.752 MiB)
  0.246053 seconds (2.56 M allocations: 74.758 MiB)
iteration 6
  0.005195 seconds (44 allocations: 9.752 MiB)
  0.273123 seconds (2.56 M allocations: 74.758 MiB, 7.64% gc time)
iteration 7
  0.005297 seconds (44 allocations: 9.752 MiB)
  0.235108 seconds (2.56 M allocations: 74.758 MiB)
iteration 8
  0.005651 seconds (44 allocations: 9.752 MiB)
  0.252498 seconds (2.56 M allocations: 74.759 MiB, 10.42% gc time)
iteration 9
  0.005433 seconds (44 allocations: 9.752 MiB)
  0.233862 seconds (2.56 M allocations: 74.758 MiB)
iteration 10
  0.005728 seconds (44 allocations: 9.752 MiB)
  0.241300 seconds (2.56 M allocations: 74.758 MiB, 7.69% gc time)
iteration 11
  0.005122 seconds (44 allocations: 9.752 MiB)
  0.227427 seconds (2.56 M allocations: 74.758 MiB)
iteration 12
  0.004810 seconds (44 allocations: 9.752 MiB)
  0.243317 seconds (2.56 M allocations: 74.758 MiB, 8.62% gc time)
iteration 13
  0.005118 seconds (44 allocations: 9.752 MiB)
  0.220562 seconds (2.56 M allocations: 74.758 MiB)
iteration 14
  0.005559 seconds (44 allocations: 9.752 MiB)
  0.243095 seconds (2.56 M allocations: 74.758 MiB, 7.51% gc time)
iteration 15
  0.004831 seconds (44 allocations: 9.752 MiB)
  0.225506 seconds (2.56 M allocations: 74.758 MiB)
iteration 16
  0.004989 seconds (44 allocations: 9.752 MiB)
  0.265440 seconds (2.56 M allocations: 74.758 MiB, 7.80% gc time)
```

**Comment by MariusDrulea** [comment]
**Update:**
I have found the code that generates the extra memory. 
The potential culplit function is in GLMakie/screen.jl. The foreach instruction inside insertplots! generates the undesired allocations. Not fully clear to me, but intuitively what happens is that when we save the figure (or scene), all it's sub-scenes are parsed and pushed into some screens in order to generate the associated image. 

I have therefore checked screen.jl in GLMakie 0.4.7 vs screen.jl in GLMakie 0.6.2 and the insertplots! function is really the same, it can be seen here: https://github.com/JuliaPlots/Makie.jl/compare/v0.15.3...v0.17.2.
What I also noticed is that in GLMakie 0.4.7 insertplots is called twice for out example, while in GLMakie 0.6.2 insertplots is called three times. 

*Important remark*:
The difference in GLMakie 0.4.7 vs GLMakie 0.6.2 is not in the save operation, but in the way `image` is created and/or in the way the update `plot_obj[1] = rand(...)` is implemented. There are more sub-scenes in GLMakie 0.6.2 compared to GLMakie 0.4.7.


```
function Makie.insertplots!(screen::GLScreen, scene::Scene)
    get!(screen.screen2scene, WeakRef(scene)) do
        id = length(screen.screens) + 1
        push!(screen.screens, (id, scene))
        return id
    end
    for elem in scene.plots
        insert!(screen, scene, elem)
    end
    foreach(s-> insertplots!(screen, s), scene.children)
end
```

**Comment by MariusDrulea** [comment]
**Update 2**:
```
using GLMakie

function show_subscenes(scene::Scene)
    println(length(scene.children))
    foreach(s->show_subscenes(s), scene.children)
end

fig, ax, plot_obj = image(rand(100, 100))

show_subscenes(fig.scene)
```

The above code prints: 1, 1, 0 for GLMakie 0.6.2 and 1, 0 for GLMakie 0.4.7. This means we have to look into how `image` was modified.

**Comment by MariusDrulea** [comment]
**Makie 0.17.2**:
I have debugged into `image` and it turned out the issue appear in 
`Makie\AW7kA\src\figureplotting.jl`, line 30: `ax = Axis(fig; axis...)`. 
And by doing a further debug inside Axis, we get into 
`Makie\AW7kA\src\makielayout\blocks.jl` line 350: 
```
blockscene = Scene(
        topscene,
        # the block scene tracks the parent scene exactly
        # for this it seems to be necessary to zero-out a possible non-zero
        # origin of the parent
        lift(Makie.zero_origin, topscene.px_area),
        camera = campixel!
    )
```
This constructor call generates the extra child scene.

**Makie 0.15.3**:
Doing the same debug we get in a different file location, but with a more or less similar implementation. 
File `Makie\gQOQF\src\makielayout\layoutables\axis.jl`, line 75: 
`scene = Scene(topscene, scenearea, raw = true)`
Here the constructor does not create an extra child scene.

**Comment by MariusDrulea** [comment]
Yet another update:
Inside the `block.jl` file (line 350) we have this code that leads to the additional child scene. I have changed this with the line bellow. This way the extra child scene is not created. However, the save operation still makes allocations, so there is something else that's causing this, some extra attributes etc. To be investigated.
```
blockscene = Scene(
        topscene,
        # the block scene tracks the parent scene exactly
        # for this it seems to be necessary to zero-out a possible non-zero
        # origin of the parent
        lift(Makie.zero_origin, topscene.px_area),
        camera = campixel!,
    )
```

changed to 
`blockscene = topscene`

**Comment by jkrumbiegel** [comment]
Yes in recent versions, each Block has its own Scene that encapsulates its content. Before, the plot objects would all just write stuff into the Figure's Scene, making it harder to clean up. I think even with this scene it should be possible to avoid unnecessary allocations though.

**Comment by MariusDrulea** [comment]
@jkrumbiegel can you please run the code bellow and put the output here in a comment, while I do more debugs. I want to see if the issue appear in several other computers. So far, me and @andrei-iosif are having this issue and we use Windows10 with nearly identical setups. Are you using Linux?

```
using GLMakie

function simple_function()
    fig, ax, plot_obj = image(rand(1664, 512), interpolate=false)
    for i in 1:100
        @time plot_obj[1] = rand(1664, 512)
        save("C:\\Temp\\fig_$i.png", fig)
    end
end

simple_function()
```

My output is bellow. As you can see, every plot update generates extra allocations and everything is being accumulated. After a significant amount of iterations the code gets very slow. Right now we still use GLMakie 0.4.7 due to this blocker.

```
 0.129497 seconds (261.74 k allocations: 24.497 MiB, 13.47% gc time, 82.51% compilation time)
  0.196099 seconds (37.73 k allocations: 14.981 MiB, 96.93% compilation time)
  0.022689 seconds (228 allocations: 16.262 MiB)
  0.007365 seconds (320 allocations: 19.517 MiB)
  0.014340 seconds (412 allocations: 22.772 MiB)
  0.010322 seconds (504 allocations: 26.026 MiB)
  0.051699 seconds (10.68 k allocations: 29.878 MiB, 44.20% gc time, 31.76% compilation time)
  0.010026 seconds (688 allocations: 32.536 MiB)
  0.011088 seconds (780 allocations: 35.791 MiB)
  0.034887 seconds (938 allocations: 39.047 MiB, 62.31% gc time)
  0.019634 seconds (964 allocations: 42.301 MiB)
  0.017382 seconds (1.06 k allocations: 45.556 MiB)
  0.066778 seconds (1.21 k allocations: 48.812 MiB, 77.67% gc time)
  0.022164 seconds (1.24 k allocations: 52.065 MiB)
  0.016710 seconds (1.33 k allocations: 55.320 MiB)
```

**Comment by SimonDanisch** [comment]
I think it's creating a new screen for each `save("...", fig)` and then completely recreates the OpenGL state from the plots, and when we close the screen and keep the fig, we don't 100% clean up what we setup for rendering in the previous screen, since there are still connections remaining.

**Comment by MariusDrulea** [comment]
@SimonDanisch your hotfix works, as seen bellow, thanks. I will debug a bit more, see how far can I get.  The furthest problematic function I was debugging is `insertplots!` called within `save`. 
```
0.292560 seconds (299.75 k allocations: 29.753 MiB, 94.96% compilation time)
  0.005291 seconds (136 allocations: 13.007 MiB)
  0.006123 seconds (136 allocations: 13.007 MiB)
  0.005618 seconds (136 allocations: 13.007 MiB)
  0.005953 seconds (136 allocations: 13.007 MiB)
  0.005409 seconds (136 allocations: 13.007 MiB)
  0.005878 seconds (136 allocations: 13.007 MiB)
  0.006206 seconds (136 allocations: 13.007 MiB)
  0.006482 seconds (136 allocations: 13.007 MiB)
  0.005584 seconds (136 allocations: 13.007 MiB)
```

**Comment by SimonDanisch** [comment]
>insertplots!


Yeah, that's the function that creates the OpenGL state from the plots in the scene

**Comment by MariusDrulea** [comment]
A small update:
I have little progress although I have spend some time debugging.
I noticed:
- the saving pipeline in GLMakie 0.6.2 is quite the same as in GLMakie 0.4.7, there are no significant modifications here
- insertplots! function is the same in GLMakie 0.6.2 and 0.4.7
- GLMakie 0.6.2 contains the new makielayout
- the function `scene2image` does the same "trick" as @SimonDanisch proposed; the latter solution however turns off the rendering in an earlier stage (image creation, the Axis layout run without rendering)
