### ISSUE TITLE
Add a `tailcolor` parameter to the `arrows` recipe ?

### ISSUE THREAD

**Issue by BambOoxX** [MakieOrg/Makie.jl#1710]
Currently, it seems possible to use `linecolor` and `arrow` color to set the color of the head and body of arrows in an arrow plot. 
However, the tail of the arrow is plotted separately, but its color is always the same than the line (see line 224).
https://github.com/JuliaPlots/Makie.jl/blob/6a0855ad3a37eac9f02a2457fe5d6ca1d52c55f6/src/basic_recipes/arrows.jl#L212-L229

It could be nice to have it customizeable. Otherwise if you plot a zero-length arrow and an nonzero-length one from the same position you can get this, i.e. the tail of the last plotted arrow one over the  previous one. 
![image](https://user-images.githubusercontent.com/42067365/156036216-87381930-067c-402c-80d1-90ae7dc7e760.png)

In this very case, i'd rather have that set as `:black` for every arrow so that there is no confusion.

This could be an optional setting, defaulting to the color of the line as current. 

To hide that behavior, I currently redraw a `meshscatter `on top of the arrows...

**Comment by ffreyer** [comment]
I think this is more of a naming issue?

Arrows used to use lines for the tail and a mesh for the head in 3D. All the arrow tail/body/shaft attributes used to be referred to as line-something because of this. https://github.com/JuliaPlots/AbstractPlotting.jl/pull/657 changed the 3D version to use a mesh for both parts but the names stayed the same. Maybe it makes sense to change a couple of names, e.g.
- linecolor to tailcolor
- arrowsize to headsize
- lengthscale to tailscale (though we should probably scale the arrow differently and have this actually affect the whole arrow #1206)

**Comment by BambOoxX** [comment]
@ffreyer Actually this behavior is on me, I got lost in the layers of my own code, my deepest apologies for the inconvenience. 
The sphere shown here was actually plotted separately. 

Regardless of my mistake, the question is still relevant, under the following form : *is it possible to draw a tail marker in addition to a head marker for the arrow ? * (and of course customize it).
