### ISSUE TITLE
LineElement in legend does not respect colormap attribute

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#1905]
Plotting a LineElement of a line with a colormap does not show a variably coloured line.  Explicitly providing `color` `colormap` to the line element results in the line being colored in the `viridis` colormap, irrespective of the colormap provided.

I will hopefully be able to push a quick PR fixing this tonight, but keeping this up here in case some issue arises.

**Comment by jkrumbiegel** [comment]
It wasn't assumed that a line would be colormapped in a legend, that's why it doesn't have that attribute.

**Comment by laikq** [comment]
This is relevant for me, since I want to refer to colors used in the plot from the legend. This also affects legends generated using `axislegend` and the `label` keyword:
```julia
x = 1:10
f, ax, _ = lines(x, x.^2; color=1, colormap=:tab10, colorrange=(1,10), label="test")
axislegend(ax)
f
```
Throws *"Cannot determine a colorrange automatically for single number color value. Pass an explicit colorrange"*, on CairoMakie v0.10.10 and Julia 1.9.3.
