### ISSUE TITLE
Misplaced yticks when mirroring inside ticks and linking yaxes

### ISSUE THREAD

**Issue by kimauth** [MakieOrg/Makie.jl#2209]
When using inside mirrored yticks, the right spines ticks seem not to be adjusted correctly upon changes to the yaxis.

```julia
set_theme!(Theme(
    Axis = (
        xticksmirrored = true,
        yticksmirrored = true,
        xtickalign = 1,
        ytickalign = 1,
    ),
))

f = Figure()
ax_t = Axis(f[1,1])
lines!(ax_t, rand(10))
ax_n = Axis(f[1,2])
lines!(ax_n, rand(10))

# linkyaxes!(ax_n, ax_t)
colgap!(f.layout, 12.)
linkyaxes!(ax_n, ax_t)
```
![misplaced_ticks1](https://user-images.githubusercontent.com/54391668/183964941-70ac7f87-5232-4c29-9f39-21f6ddef98e3.png)

When swapping the `linkyaxes!` and `colgap!` commands, the ticks end up in a different position, but still not really correct:
![misplaced_ticks2](https://user-images.githubusercontent.com/54391668/183964978-32dce383-4188-4032-9d79-c63d7dd87b7e.png)

This is on `Makie v0.17.13`.

**Comment by kimauth** [comment]
Here is another example of this, without linking axes this time. It's an [example from the docs](https://makie.juliaplots.org/dev/examples/plotting_functions/contourf/#contourf), I only added the `yticksmirrored` option.
```julia
using CairoMakie
using DelimitedFiles

volcano = readdlm(Makie.assetpath("volcano.csv"), ',', Float64)

f = Figure()
Axis(f[1, 1]; yticksmirrored=true)

co = contourf!(volcano, levels = 10)

Colorbar(f[1, 2], co)

f
```
![misplaced_ticks_contourf](https://user-images.githubusercontent.com/54391668/184629902-b6e1966c-e0f1-44bd-9236-d9d5ff80c0e6.png)

**Comment by jkrumbiegel** [comment]
Yes good catch, there were some edits to observable updates with ticks a while ago, those must have broken whatever the mirroring uses. Or the mirroring itself was buggy from the start and just not visible in my specific tests.

**Comment by adityanprasad** [comment]
I have the same problem, except in addition to being misaligned, my mirrored inner-ticks also end up on the outside. This is without linking any axes. 

```julia
	X = rand(100) .+ 100
	
	f = Figure()
	axisargs = (
			xticksmirrored=true,
			yticksmirrored=true,
			xtickalign=1,
			ytickalign=1, 
	)
	
	scatter(f[1,1], X, axis=(;axisargs...,))
	scatter(f[1,2], X .* 10, axis=(;axisargs...,),)
	scatter(f[2,1], X, axis=(;axisargs...,))
	scatter(f[2,2], X .* 10, axis=(;axisargs...,),)
```
![yticks-bug-linear](https://user-images.githubusercontent.com/9686293/185013774-2db3ae3e-4756-4dd2-9522-09991103c21a.png)

Weirdly enough, this only seems to affect the plot at GridPosition[1,1] if it is created first. If I switch the order of construction, Makie seems to fix itself.

```julia
	X = rand(100) .+ 100
	
	f = Figure()
	axisargs = (
			xticksmirrored=true,
			yticksmirrored=true,
			xtickalign=1,
			ytickalign=1, 
	)
	
	scatter(f[1,2], X .* 10, axis=(;axisargs...,))
	scatter(f[1,1], X, axis=(;axisargs...,),)
	scatter(f[2,1], X, axis=(;axisargs...,))
	scatter(f[2,2], X .* 10, axis=(;axisargs...,),)
```
![yticks-bug-linear-fix](https://user-images.githubusercontent.com/9686293/185014073-5c6715b4-d5cb-438d-af72-3d3463bd6f4b.png)

Btw, would it be possible to rename `xticksmirrored` to `xtickmirrored` (i.e. singular instead of plural). `xticksmirrored` and `xminorticksmirrored` are the only attributes that are plural: compare this to `xtickalign`, `xtickcolor` `xtickformat` etc. The only exception seems to be `xticks`, which you could justify because of common usage and the fact that it expects a range of values.


I am using `Julia Version 1.8.0-rc3` on an M1 Mac and `GLMakie v0.6.13`

**Comment by jkrumbiegel** [comment]
was fixed in https://github.com/MakieOrg/Makie.jl/pull/3581
