### ISSUE TITLE
Axis3 displays nothing if you try and use latex in the z-label

### ISSUE THREAD

**Issue by jkharv** [MakieOrg/Makie.jl#2260]
While trying to make a surface plot I found that Axis3 breaks if you try and use latex in the z-label. Below is a working example

```julia
using CairoMakie

fig = Figure(resolution = (800, 800));
ax = Axis3(fig[1,1],
           height = 600,
           width = 600,
           xlabel = L"x",
           ylabel = L"y",
           zlabel = L"z")
xs = LinRange(0, 10, 100);
ys = LinRange(0, 15, 100);
zs = [cos(x) * sin(y) for x in xs, y in ys];

surface!(ax, xs, ys, zs)
fig
```
The above code produces

![plot_49](https://user-images.githubusercontent.com/10576780/188701406-5e6e28ae-2f4d-4dd6-943a-a835a1c02095.png)

while the same code using `zlabel = "z"` produces

![plot_50](https://user-images.githubusercontent.com/10576780/188701606-adce0a0b-df9a-4b22-be89-56dc08260dc5.png)

When using `GLMakie` instead of `CairoMakie` the surface draws into the axis perfectly but the zlabel simply does not appear.

![Screenshot from 2022-09-06 13-34-03](https://user-images.githubusercontent.com/10576780/188702322-98a307da-9566-4d14-aacb-d0d0ac879f87.png)

This was running on Fedora 36 Workstation edition with an AMD graphics card, julia version 1.7.3,
CairoMakie v0.7.4, and GLMakie v0.5.4.

I got the same results on a computer which used Nvidia graphics and the same OS version but I don't remember for sure the other versions (most likely the same).

**Comment by fatteneder** [comment]
What versions of `Makie, GLMakie, CairoMakie` and `Julia` itself are you running?

I cannot reproduce the problem, tested with
```julia
  [13f3f980] CairoMakie v0.8.13
  [e9467ef8] GLMakie v0.6.13
  [ee78f7c6] Makie v0.17.13
```
and `Julia v1.8.0`.

**Comment by fatteneder** [comment]
It is strange that updating julia itself fixed it. Also because I now tested with `v1.7.3.` and the same version of the Makie packages I mentioned above and still cannot reproduce the problem. This is what I see now: 

![image](https://user-images.githubusercontent.com/26469701/188958295-097737d9-7162-4110-91be-25a8407b6643.png)

Maybe it is some issue with your graphics card driver?
I don't have much experience in this area. I can only say I am testing on Intel Xe Graphics.
But then the issue also appears with `CairoMakie` which should not depend on the graphics driver, I think ...

**Comment by jkharv** [comment]
Hmm that is strange since I had this problem on different computers with intel integrated, AMD, and Nvidia cards respectively. If I get more time in the near future I'll try and do some more testing.

**Comment by SimonDanisch** [comment]
This seems fixed
