### ISSUE TITLE
CairoMakie: bug with transparent colormap

### ISSUE THREAD

**Issue by m-leroy** [MakieOrg/Makie.jl#2302]
Hello,

I am experiencing a problem with transparent colormap when using CairoMakie. The problem does not happen when using GLMakie, as you can see with the following figures:
![CairoMakie-test](https://user-images.githubusercontent.com/8538174/192455761-159700a8-50d1-45f2-97f4-b5986c16572c.png)
![GLMakie-test](https://user-images.githubusercontent.com/8538174/192455752-93332a63-581d-4188-8194-92f7885c10e7.png)

MWE:
```
using CairoMakie

CairoMakie.activate!()
x = collect(0:100.0)
y = collect(0:100.0)
z = x .* y'
f = Figure()
ax = Axis(f[1, 1], title="CairoMakie")
heatmap!(ax, x, y, z, colormap=(:viridis, 0.25))
save("CairoMakie-test.png", f)
f

using GLMakie

GLMakie.activate!()
x = collect(0:100.0)
y = collect(0:100.0)
z = x .* y'
f = Figure()
ax = Axis(f[1, 1], title="GLMakie")
heatmap!(ax, x, y, z, colormap=(:viridis, 0.25))
save("GLMakie-test.png", f)
f
```

Librairies versions:
```
  [13f3f980] CairoMakie v0.8.13
  [e9467ef8] GLMakie v0.6.13
  [ee78f7c6] Makie v0.17.13
```

OS info:
```
Microsoft Windows 10 Entreprise
Version	10.0.19042 Build 19042
```

Best regards.

**Comment by jkrumbiegel** [comment]
Cairo has some problems with transparency it seems. I haven't yet pinned down which cases exactly are problematic but I suspect they always involve bitmaps with transparency.

**Comment by m-leroy** [comment]
> Cairo has some problems with transparency it seems. I haven't yet pinned down which cases exactly are problematic but I suspect they always involve bitmaps with transparency.

Indeed, _.SVG_ and _.PDF_ have no problems. SVG example:
![CairoMakie-test](https://user-images.githubusercontent.com/8538174/192466946-07df36aa-ac37-4e86-9d54-a3ca8152eb5c.svg)

VSCode plot window seems to use PNG.

**Comment by jkrumbiegel** [comment]
hm ok but that was not even what I meant, I was talking about bitmap components drawn by cairo, not bitmap output format. because there have been issues reported with images with transparency in pdf output (see for example https://github.com/MakieOrg/Makie.jl/issues/2162). But interesting that the bad output is png in your case, because that was fine in the other one. If it's indeed a Cairo issue (and there's not much room for error for us in passing an rgba array to Cairo), there's not much we can do. But maybe someone can dig up some info about this on the web and there might be workarounds we can use.

**Comment by jkrumbiegel** [comment]
Ok interesting I have a theory. It seemed to me that the colors were kind of the right direction (so not a complete screw-up of the image data) but that they are maybe composited differently than the default. This is how a small heatmap with alpha 0.5 looks in VSCode:

<img width="612" alt="grafik" src="https://user-images.githubusercontent.com/22495855/192506188-6d0cddeb-3369-439a-9bce-a66b217b7519.png">

Then I took a screenshot of a version without alpha:

<img width="587" alt="grafik" src="https://user-images.githubusercontent.com/22495855/192506282-81d7a07f-5ab1-4faa-9798-78dd3f9fe818.png">

And put that into photoshop where I tried out different drawing operators. "Hard light" with 0.5 alpha seemed to be a hit:

<img width="469" alt="grafik" src="https://user-images.githubusercontent.com/22495855/192506413-07e51e4e-41e1-4fde-9b34-5d5b4543a5d5.png">

I checked with `Cairo.get_operator` that the operator used in the moment the heatmap was drawn was 2, which should be the default "over" as seen in this list https://www.cairographics.org/manual/cairo-cairo-t.html#CAIRO-OPERATOR-OVER:CAPS

So it seems that Cairo for some reason draws with "Hard light" mode or something similar, instead of over, when alpha is present. And I think this only matters in png because the other backends don't support the blend mode and use the default one, or it's just a png backend bug.

**Comment by m-leroy** [comment]
I suspected a problem of that kind too.
It reminds me when I was playing with image blend mode in Photoshop or Gimp.

**Comment by jkrumbiegel** [comment]
Ok I finally understand the issue. It's super simple actually... Cairo surfaces need premultiplied alpha and we never noticed that. I guess it's not totally obvious from the documentation and you only see it when you use transparent colors.

This pr should fix it: https://github.com/MakieOrg/Makie.jl/pull/2304
