### ISSUE TITLE
CairoMakie saving raster to .svg depending on content

### ISSUE THREAD

**Issue by jaakkor2** [MakieOrg/Makie.jl#2396]
In this example, file `debug2.svg` is 75 kB and contains the png raster of the output.  `debug1.svg` is 20 kB and contains the vector graphics as intended.
```
using CairoMakie
CairoMakie.activate!(type="svg")
using Makie.GeometryBasics

item1 = Point2.([[0,0],[1,0],[0,1],[0,0]])
item2 = Point2.([[0,0],[1,0],[0,-1],[0,0]])
fig = Figure()
ax = Makie.Axis(fig[1,1])
Makie.poly!(ax, MultiPolygon([Polygon(item1)]), color = :red)
save("debug1.svg", fig) # vector (ok)
Makie.poly!(ax, Polygon(item2), color = :blue)
save("debug2.svg", fig) # png raster inside .svg (why?)
```

Project has only CairoMakie, manifest lists CairoMakie 0.9.1, Cairo 1.0.5, Cairo_jll 1.16.1+1, Makie 0.18.1, MakieCore 0.5.1, GeometryBasics 0.4.2, GeoInterface 1.0.1, Julia 1.8.2.

**Comment by jkrumbiegel** [comment]
`poly` has special override functions in CairoMakie so that it doesn't need to fall back to `mesh` which it is based on in general. If `mesh` is hit, then the whole cairo context gets rasterized as mesh drawing is not supported in svg. So one of your cases must hit mesh even though it's not supposed to.
