### ISSUE TITLE
Multiple plots don't show all 

### ISSUE THREAD

**Issue by andreasvarga** [MakieOrg/Makie.jl#2460]
I have generated two figures with CairoMakie, say Fig1 and Fig2, which I can visualize in REPL by simply typing 
```
Fig1
Fig2
```
On Windows 10, each plot appears in a separate window. Following the recommendation in [#519](https://github.com/MakieOrg/Makie.jl/issues/519#issuecomment-1328105136), I generated the figures with the setting

`Makie.inline!(false)`

However, if the same sequence is included in a script file, then only the figure Fig2 shows up when executing the script file with `include`. If I am copying and pasting the above code snippet into the REPL, Fig2 shows up twice, in separate windows. Is any way to enforce the same behaviour in scripts or when using copy-paste as from executing successively the commands in REPL?

**Comment by jkrumbiegel** [comment]
Typing something in the Repl calls `display(x)` on the result `x`. This doesn't happen for intermediate results in some code you `include`, however the last value from that code will again be `display`ed because every expression in Julia returns a value, and so does `include`. You need to call `display(x)` inside your script if you want plot `x` to show.
