### ISSUE TITLE
Poly with transparancy broken on CairoMakie@0.9.4

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/Makie.jl#2469]
```julia
using Pkg
pkg"activate --temp"
pkg"add CairoMakie@0.9.4"
using CairoMakie
using CairoMakie.Colors
fig, ax, p = poly(Circle(Point2f(0, 0), 10), color=RGBA(0.0,0.44705883,0.69803923,0.2))
save("plot094.png", fig)
```
![plot094](https://user-images.githubusercontent.com/35867212/205609598-7259b9ff-85ed-4c4c-bf02-2cd9c973fc75.png)

works fine in 0.9.3
```julia
using Pkg
pkg"activate --temp"
pkg"add CairoMakie@0.9.3"
using CairoMakie
using CairoMakie.Colors
fig, ax, p = poly(Circle(Point2f(0, 0), 10), color=RGBA(0.0,0.44705883,0.69803923,0.2))
save("plot093.png", fig)
```

![plot093](https://user-images.githubusercontent.com/35867212/205609583-47daebb5-2c13-4dbc-bb7e-662b3b3f50e6.png)

not a problem in current or past verisons of GLMakie.

xref https://github.com/MakieOrg/GraphMakie.jl/pull/95

**Comment by fatteneder** [comment]
Now I remember that I had a similar issue when implementing `poly` in `SVGMakie.jl`.
I worked around that by setting the outline's stroke color and transparency to the same as the fill, see https://github.com/fatteneder/SVGMakie.jl/blob/c764e5b1658a677429e35ce244bbde5b8473d5e1/src/overrides.jl#L216-L218

Maybe that could be applied here too?
Although it seems weird, because unless you call `Cairo.stroke` there shouldn't be any outlines ...

**Comment by jkrumbiegel** [comment]
The fix here is to make this kind of polygon not hit the mesh drawing routines, something in the dispatch setup must miss it.
