### ISSUE TITLE
[FR] `rich` text rotation

### ISSUE THREAD

**Issue by t-bltg** [MakieOrg/Makie.jl#2479]
It'd be great if `rich` text supported arbitrary text rotation:
```julia
julia> using CairoMakie
julia> lines(0..2π, sin; axis = (; xlabel = "x", ylabel = rich("y"; rotation = 0)))
```

In the mean time, arbitrary 2D axis labels rotation will be added in https://github.com/MakieOrg/Makie.jl/pull/2478.

**Comment by jkrumbiegel** [comment]
I'll close this as not planned because I don't currently see how within-text rotation can be useful, while it would add some complexity to the layout algorithm. It seems to me that you really wanted to modify the rotation of the whole text, but that's not what a setting within `rich` would do. That would influence per-glyph attributes.

If you can come up with visual examples that make the case that within string glyph rotation is useful, I'll reconsider.
