### ISSUE TITLE
WGLMakie + Pluto plot cuts off

### ISSUE THREAD

**Issue by eahenle** [MakieOrg/Makie.jl#2499]
Using WGLMakie 0.8.0 & Pluto 0.19.17, the right-hand side of every plot is cut off, like so:

![image](https://user-images.githubusercontent.com/16201240/207408057-bef07763-3af7-47d2-9c60-630beae1e444.png)

Unlike #2438 / #2440 / #2444, this does not depend on any previous calls, figure saving, or re-drawing, but will occur on the first (and all subsequent) calls to any plotting function.  Still, I wonder if the issue is related to what was going on with `CairoMakie` in those issues?

**Comment by SimonDanisch** [comment]
WGLMakie without `Page` doesn't surprise, since it falls back to displaying in an iframe, making this a duplicate of https://github.com/MakieOrg/Makie.jl/issues/2358...
All such issues and the need for `Page` should be resolved in https://github.com/MakieOrg/Makie.jl/pull/2428.

@juliohm for other backends, I need an MWE, where I can reproduce the cut off...

**Comment by eahenle** [comment]
@SimonDanisch Ah, OK, sounds like this issue can be closed, then (if @juliohm has something else to add, probably opening a new issue specific to that is appropriate)

**Comment by juliohm** [comment]
@SimonDanisch I think some of the tests we have are cut off, for example: https://github.com/JuliaGeometry/MeshViz.jl/blob/a79f9e9051b9820a6b694b871533af5bc58486d2/test/data/gridview2D-1.png

These are all produced with CairoMakie. I have also seen similar cutoffs with GLMakie, and will keep them in mind next time they appear.
