### ISSUE TITLE
visible attribute on vlines! not working for GLMakie and WGLMakie

### ISSUE THREAD

**Issue by Arch-Storm** [MakieOrg/Makie.jl#2502]
```
f = Figure()
ax = Axis(f[1, 1])
limits!(ax, 0, 3, 0, 3)
vlines!(ax, [1], color = :red, visible = false)
vlines!(ax, [2], color = :green)
f
```
Produces this using CairoMakie as expected:
<img src="https://user-images.githubusercontent.com/42775469/207594648-c7d55785-ee22-42c4-83fb-b9793b9a6a85.png" width="400">
But produces this using GLMakie & WGLMakie:
<img src="https://user-images.githubusercontent.com/42775469/207594759-e6f128b2-cbbe-4ec4-b8e3-f24df48a292c.png" width="400">

**Comment by SimonDanisch** [comment]
I'm guessing this happens because (W)GLMakie always expand the plot recipes to their atomic plots, so if the recipe doesn't forward the visible attribute, they will still render it... CairoMakie likely always checks the attributes and stops rendering. 
I'm not sure if we can easily to the same as CairoMakie, since the backend never sees the recipes, and checking visibility before expanding & inserting the plots would mean, not to insert them at all...

**Comment by SimonDanisch** [comment]
I guess the cleanest solution would be to always make sure, that recipes forward key attributes like visibility automatically...
