### ISSUE TITLE
`contour`: `linestyle` works only in very limited cases

### ISSUE THREAD

**Issue by f3fora** [MakieOrg/Makie.jl#2503]
`contour` with `linestyle` option does not work as expected in most of the cases.

Expected behavior is something like this:
 
```julia
let
    f = Figure()
    ax = Axis(f[1, 1])
    contour!(ax,
        1:10,
        1:10,
        +;
    	linestyle=:dash, linewidth=1
    )

    f
end
```

Increasing `xrange` and `yrange` (e.g. 1:1000), produces a solid lines if `linestyle` is a Symbol, else if the `linestyle` is a vector no line is printed.

**Comment by jkrumbiegel** [comment]
Are you using GLMakie or CairoMakie? GLMakie has problems drawing linestyles with lines built from many small segments, because each line segment needs to be drawn separately, so linestyles are only consistent within a segment. This breaks down if the resolution becomes too high. With CairoMakie you won't have that problem as it will "walk" along the line and stroke whenever some distance has been covered.

**Comment by f3fora** [comment]
With both.

**Comment by wsshin** [comment]
I am experiencing the same issue.  Here is an MWE:
```julia
using CairoMakie
fig = Figure()
fig[1,1] = Axis(fig)
N=100  # number of data points in each axis
xs = ys = range(0, 1; length=N)
contour!(xs, ys, +, linestyle=:dash)
display(fig)
```
This produces
![N=1000](https://user-images.githubusercontent.com/1783289/230955250-31e05d0e-f344-4d9a-adb1-1ea0cae703a0.png)

On the other hand, if we reduce `N` to `100`, we get the correct line style:
![N=100](https://user-images.githubusercontent.com/1783289/230955436-3e9d4f71-8d39-4c56-b934-a45f9d2730ab.png)

Here is the version info:
```
julia> VERSION
v"1.9.0-rc2"

(@v1.9) pkg> st -m Makie
Status `~/.julia/environments/v1.9/Manifest.toml`
  [ee78f7c6] Makie v0.19.4

(@v1.9) pkg> st CairoMakie
Status `~/.julia/environments/v1.9/Project.toml`
  [13f3f980] CairoMakie v0.10.4
```

**Comment by SimonDanisch** [comment]
This seems to be fixed
