### ISSUE TITLE
`WGLMakie` test suite `IOError: write: broken pipe (EPIPE)`

### ISSUE THREAD

**Issue by t-bltg** [MakieOrg/Makie.jl#2561]
This error also occurs in ci on master (https://github.com/MakieOrg/Makie.jl/actions/runs/3839920174/jobs/6538335883#step:7:602).

@SimonDanisch I don't know what causes this (happens locally, but spuriously e.g. on `running  39: heatmap_interpolation`), and this prevents me from fully testing / validating https://github.com/MakieOrg/Makie.jl/pull/2493.

EDIT: trying now with `JSServe@2.0.3`
=> no, still occurs e.g. in https://github.com/MakieOrg/Makie.jl/actions/runs/3850508434/jobs/6560728162#step:7:655.

**Comment by SimonDanisch** [comment]
I think this should be a non fatal error, is it not?

**Comment by t-bltg** [comment]
It is non-fatal, but it's confusing.

**Comment by SimonDanisch** [comment]
I think this happens when we send messages to an almost closed session, so that the `isopen(ws)` still returns true, but then while writing, the websocket closed. 
I added this, which will hopefully fix it: https://github.com/SimonDanisch/JSServe.jl/pull/143/commits/572343ecde545cbea1d1d5c183414be31ee74754

**Comment by t-bltg** [comment]
Thanks for the explanation, and the fix.
I seem to hit this less often after updating to `JSServe@2.0.3`, so this is not blocking anymore.
