### ISSUE TITLE
Save figure using the backend argument leaves empty figure behind

### ISSUE THREAD

**Issue by bilderbuchi** [MakieOrg/Makie.jl#2675]
When you have an interactive figure (GLMakie) it is possible to save it to a pdf using CairoMakie. However, doing so leaves an empty figure window behind:

```julia
using CairoMakie, GLMakie
fig, ax = lines(rand(5), rand(5))
save("test.pdf", fig; backend=CairoMakie)
```
CairoMakie v0.10.2
GLMakie v0.8.2
Makie v0.19.2

@SimonDanisch points to a possible [fix location](https://github.com/MakieOrg/Makie.jl/blob/9aee7d4217f8a880669d346862c76100268cd827/src/display.jl#L33):

> I don't have much time to fix this, but it's very likely this part: https://github.com/MakieOrg/Makie.jl/blob/master/src/display.jl#L33
I think we need to losen that up to allow one screen _per_ backend! 
This should fix the issue. 

_Originally posted by @SimonDanisch in https://github.com/MakieOrg/Makie.jl/issues/1960#issuecomment-1425979462_

**Comment by pbouffard** [comment]
@SimonDanisch [suggested](https://julialang.slack.com/archives/C8RQUU2KH/p1676398367733949?thread_ts=1676393404.062009&cid=C8RQUU2KH) on Slack that I post here about a related use case.

I'd like to be able to take the same 3D scene (lowercase 's') -- which I think basically is represented in Makie by a `Scene` but possibly there's not a full 1:1 correspondence -- and have additional views of it in other places. Those views would primarily be from different cameras and with different window sizes, though being able to change other aspects, such as lighting, textures, wireframe, camera parameters (especially ortho/perspective), etc. would be useful too. This is in the context of GLMakie and interactive visualizations so I mean that updating the main scene should result in the same update being instantly reflected in the additional views.

It would be a nice plus to be able to have some interactivity in the secondary view(s) but just having them be 'read-only' would be the most useful aspect.

(PS. Since the Slack thread link will stop working after awhile, a screenshot of the thread):

![image](https://user-images.githubusercontent.com/231346/218824201-817aafb2-0c89-4119-b567-5a2e79ae0015.png)

**Comment by bilderbuchi** [comment]
Thanks for fixing this!
