### ISSUE TITLE
Feature request: super-above-subscript

### ISSUE THREAD

**Issue by sefffal** [MakieOrg/Makie.jl#2718]
It would be really handy to be able to put superscript rich text above subscript rich text. 
My main usecase for this is the PairPlots.jl library that's now built on Makie. For now, I am using LaTeX but this causes the fonts not to match and prevents me from applying matching colors to text, just because it is typeset with this kind of superscript/subscript.

See this discourse link for context: https://discourse.julialang.org/t/ann-a-package-for-generating-corner-plots-pairplots-jl/58542/22

**Comment by jkrumbiegel** [comment]
I had this and removed it, because I wasn't sure about the consequences for line breaking. Because then the x offset doesn't continously move forward, it jumps back for the subscript and that complicates things a bit. I haven't actually implemented the word-wrap-width linebreaking for rich text anyway, but it would still have to work with that once we get to it. In principle, I'm all for it.

**Comment by briochemc** [comment]
+1 for this feature! I had to do some manual offset adjustments to do the sub/superscripts in the title and ylabel in this plot (and it's not perfect as you may be able to tell):

![Image](https://github.com/user-attachments/assets/0671913b-1a36-4f95-a3fc-48c5553529db)

I'm sure I'm missing something, but could you not have a `subsuperscript("sub", "super")` function where the offset is just the maximum of the offsets of `subscript("sub")` and `superscript("super")`?
