### ISSUE TITLE
CairoMakie seems to add round caps to lines

### ISSUE THREAD

**Issue by SimonDanisch** [MakieOrg/Makie.jl#2934]
Just saw this in the reference tests:
Reference picture:
![image](https://user-images.githubusercontent.com/1010467/236857031-923c9790-152e-43a3-9e01-d9475944bc2f.png)
CairoMakie:
![image](https://user-images.githubusercontent.com/1010467/236857158-18f598e4-3f95-4712-9334-90a1b1f9dd13.png)

If I'm not mistaken, those "bars" are drawn as separate polygons via `poly!(scene, vector_of_rect2f)`.

I suspect some global state somehow setting the rects to be rounded?
I did notice in #2918, that `draw_poly` doesn't seem to store / restore the context?

**Comment by asinghvi17** [comment]
The state is reset every time we enter a new Scene in the `cairo_draw` function as we iterate across plots.  Could be some global setting, but since this particular Scene only contains these two plots I don't think it's this. Could definitely be some global state - or just that line joins are set to rounded.

**Comment by jkrumbiegel** [comment]
just to repeat that info, the rounded caps are a little visual optimization for `lines` with different colors along the line. because cairo has to draw each segment separately, the round caps avoid gaps at the joints. One could also calculate joins manually and draw everything as polygons, but maybe that's very slow in comparison

**Comment by ffreyer** [comment]
This is not happening anymore
