### ISSUE TITLE
`colgap` and `rowgap` behave weirdly after creating an inset axis

### ISSUE THREAD

**Issue by thudjx** [MakieOrg/Makie.jl#2975]
The MWE goes like:
```
let
	fig = Figure()
	ax1 = Axis(fig[1,1], xaxisposition=:top)
	ax2 = Axis(fig[2,1])
	inset_box = Axis(fig[1,1], width=Relative(0.4), height=Relative(0.2), halign=0.45, valign=0.25)
	rowgap!(fig.layout, 0)
	fig
end
```
The `rowgap!` is not working correctly:
![image](https://github.com/MakieOrg/Makie.jl/assets/32637321/a4df37de-7700-4ca9-89e7-c8050707695b)
However, if we change the line creating the `inset_box` into:
```
inset_box = Axis(fig[2,1], width=Relative(0.4), height=Relative(0.2), halign=0.45, valign=0.25)
```
everythings go back to normal:
![image](https://github.com/MakieOrg/Makie.jl/assets/32637321/26fae35a-5910-433f-babc-c0c3d0886b99)
The same issue comes with `colgap` and the MWE is here:
```
let
	fig = Figure()
	ax1 = Axis(fig[1,1])
	ax2 = Axis(fig[1,2], yaxisposition=:right)
	inset_box = Axis(fig[1,1], width=Relative(0.4), height=Relative(0.2), halign=0.45, valign=0.25)
	colgap!(fig.layout, 0)
	fig
end
```
The `inset_box` created this way works correctly but this does not:
```
inset_box = Axis(fig[1,2], width=Relative(0.4), height=Relative(0.2), halign=0.45, valign=0.25)
```

**Comment by jkrumbiegel** [comment]
This just looks like `rowgap` doesn't work, but the actual effect is that you reduce the width/height of the additional axis, but its lower protrusions still request that space to be reserved. This is because it requests the maximum amount of space needed, not the one currently needed (as it depends on the overall space available and thus changes when the layout is recomputed). You can probably set `inset.alignmode = Outside(0)` so it doesn't have protrusions. In the future, there will probably be more convenient functions added to create inset axes that avoid this.
