### ISSUE TITLE
themeing does not work for figure resolution

### ISSUE THREAD

**Issue by jonathanlilly** [MakieOrg/Makie.jl#2988]
Hi,

In creating a theme, I notice that I can't set the figure resolution.  The following will correctly set the figure background but not its resolution.  

lineplottheme=Theme(
    Figure = (backgroundcolor = :transparent,resolution = (2000, 1500))
)

set_theme!(lineplottheme)
f = Figure()

To set the resolution, I have to do this:

lineplottheme=Theme(
    Figure = (backgroundcolor = :transparent,)
)
resolution = (2000, 1500)

set_theme!(lineplottheme)
f = Figure(;resolution); 

I'm not sure whether or not this is a bug.  If it is not a bug, it would be helpful to have a list of which properties one cannot set with Theme, which I have been unable to locate.

Thanks!

**Comment by jkrumbiegel** [comment]
These keys shouldn't be grouped under `Figure`. This is a bit inconsistent with the other theme keys like `Axis` etc., but it's because the `Figure` was considered to be the "base layer" at the time, so its attributes are at the top-level. https://github.com/MakieOrg/Makie.jl/blob/master/src/theming.jl#L54

**Comment by jonathanlilly** [comment]
Perfect, this works now!  Thanks so much!

lineplottheme=Theme(
   backgroundcolor = :transparent,
   resolution = (2000, 1500)
)

set_theme!(lineplottheme)
f = Figure()
