### ISSUE TITLE
Horizontal spacing strangely adjusted for Axis3

### ISSUE THREAD

**Issue by LukasBarner** [MakieOrg/Makie.jl#3019]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
Apple M1 Max, macOS Ventura Version 13.0

---
First of all, thanks for the amazing Package 😄

See below the result for the following MWE: 

```Julia
using Makie, CairoMakie

p_wind_daily = reshape(1:8760, 24, 365)
p_solar_daily = reshape(1:8760, 24, 365)

fig = Figure()
ax1 = Axis3(fig[1,1], xlabel = "Hour", ylabel = "Day", zlabel = "P[MW]")
ax2 = Axis3(fig[1,2], xlabel = "Hour", ylabel = "Day", zlabel = "P[MW]")

surface!(ax1, 1:24, 1:365, p_wind_daily, colormap = :inferno)
surface!(ax2, 1:24, 1:365, p_solar_daily, colormap = :inferno) 

save("/path/to/tbd/figure.pdf",fig)
```
Also, the resulting pdf file may be corrupt as it has nearly 20MB and is displaying much slower than other plots produced e.g. on a 2D Axis.
Might this be related to other things such as #1492?
If I can be of any help in fixing this, please let me know. 
Attached is a lower resolution screenshot of the pdf, if it helps I can also provide the original file.

<img width="907" alt="Screenshot 2023-06-20 at 18 37 38" src="https://github.com/MakieOrg/Makie.jl/assets/90325652/21a56fa7-1e30-486d-9aef-8555dcdb1b2b">

**Comment by LukasBarner** [comment]
See also this screenshot from the docs, where the z-label is strangely adjusted (taken from https://docs.makie.org/stable/tutorials/layout-tutorial/)

<img width="770" alt="Screenshot 2023-06-20 at 18 47 58" src="https://github.com/MakieOrg/Makie.jl/assets/90325652/3f22cd1b-e97d-4121-a41a-c96c8c7c4db2">

**Comment by jkrumbiegel** [comment]
Axis3 does not have auto-protrusions like Axis does, because the decorations don't stick out nicely separated into horizontal and vertical components, and there's rotation and perspective playing a role. So if Axis3 currently takes too little / too much space in the column gaps you can adjust the `protrusions` attribute https://docs.makie.org/stable/examples/blocks/axis3/#protrusions (not a visual example there yet, though).

The file size of 20MB should be because the surface is decomposed into a lot of triangles. You could try passing `rasterize = 1 # or 2, 3, ...` to the surface so that it's drawn as a single image instead.

The image from the docs shows the same problem as I explained above. It's just trickier for 3D to compute this, as the values change when the layout shifts (that's not generally the case for Axis).

**Comment by LukasBarner** [comment]
Thanks a lot for the quick reply 😄 
Can I close the issue since this is not a bug? Or should this be documented somewhere, e.g. in the layout tutorial above?

**Comment by jkrumbiegel** [comment]
The tutorial includes this section currently:

> Note that the z label overlaps the plot to the left a little bit. Axis3 can't have automatic protrusions because the label positions change with the projection and the cell size of the axis, which is different from the 2D Axis.
> 
> You can set the attribute ax3.protrusions to a tuple of four values (left, right, bottom, top) but in this case we just continue plotting until we have all objects that we want, before we look if small tweaks like that are necessary.

I'm going to close this issue, although I still want to add a visual example for `protrusions` to the Axis3 page.
