### ISSUE TITLE
[docs] documentation for using legend is missing

### ISSUE THREAD

**Issue by daviehh** [MakieOrg/Makie.jl#308]
With the current documentation, look like the page for the usage of legends is missing:
http://makie.juliaplots.org/stable/search.html?q=legend
returns no results. Is it intentional/legend renamed to something else or just a documentation generation issue? Thanks!

**Comment by SimonDanisch** [comment]
Legends aren't supported in the way I would like to have them - yet... So that's why there is no documentation.
Note that there are examples though, that show how to use legends:
https://simondanisch.github.io/ReferenceImages/gallery///color_legend//index.html
https://simondanisch.github.io/ReferenceImages/gallery///labels//index.html

Can be found in the gallery:
https://simondanisch.github.io/ReferenceImages/gallery/index.html

Although legend is badly named, so one needs to search for "labels"

**Comment by asinghvi17** [comment]
Via SImon: 
> camera = campixel! is needed to have a concrete boundingbox in pixel units, so that the layouting in vbox can automatically give it the right size!

**Comment by daviehh** [comment]
work-in-progress: write a function/recipe that aims to work like `plot` in `Plots.jl`, [here](https://github.com/JuliaPlots/Makie.jl/issues/302#issuecomment-469447832)

**Comment by felixcremer** [comment]
This should be closed. Legends are documented here https://docs.makie.org/stable/examples/blocks/legend/index.html

**Comment by daviehh** [comment]
@felixcremer ok, thanks!
