### ISSUE TITLE
GLMakie and WGLMakie display sizes in IJulia very different

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#3184]
- [x] are you running newest version (version from docs) ? Julia 1.10 beta-2, WGLMakie v0.8.12, GLMakie v0.8.8, IJulia v1.24.2
- [x] What platform + GPU are you on? Mac M1

The size of a displayed, inline image is very different between GLMakie and WGLMakie, e.g., when executed inside a Jupyter notebook. The two rendered images look quite close, and share the same resolution, but the GLMakie image is displayed larger by almost a factor of two. Please see image below.

<img width="585" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/290205/b13d0a8d-104e-43b8-a275-a693c7ed9234">

Ideally Makie would be consistent in image size. Until that is fixed, is there a workaround to control the display image size? The named parameter `resolution` will make an image bigger, but at the cost of making the marker and font size smaller.

By the way, the attached image shows another strange behavior. Executing `using GLMakie` and then `using WGLMakie` will switch the rendering backend. But then executing `using GLMakie` again will not switch back.

**Comment by jkrumbiegel** [comment]
This should be mostly fixed in the 0.20 beta (you could try it out?). The reason for the x2 size of GLMakie is that you're on a x2 pixel density system, so 1 CSS px == 2 screen pixels. The WGLMakie figure gives its own resolution in the html code, while the GLMakie figure is just an embedded png without further size information. This is changed in the beta so that a GLMakie png should also be embedded via html code that tells the page what the actual intended size of the image is. (On GLMakie, you will then also be able to increase `px_per_unit` to make things sharper).

Actually, the size of GLMakie is already the "correct" one here (in terms of logical pixel size), it just doesn't look too good because the image is rendered with pixel density 1. In the beta, both WGLMakie and GLMakie should have the size of the currently blurry image, but you should be able to make both sharp.

> Executing using GLMakie and then using WGLMakie will switch the rendering backend. But then executing using GLMakie again will not switch back.

I think `activate!()` is being called in `__init__()`, but this runs only at the first `using`.

**Comment by kbarros** [comment]
I think this is the result with `git checkout sd/beta-20`. The GLMakie result became high-res (nice!) but the visual display size still seems different.

<img width="404" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/290205/631d0c4d-1ef2-4d2d-a739-4987cf2ca8bd">

**Comment by jkrumbiegel** [comment]
Ehh maybe it was this one for WGLMakie then https://github.com/MakieOrg/Makie.jl/pull/3062 in which Simon started to merge the beta in a while ago

**Comment by kbarros** [comment]
Indeed, with the `sd/wgl-lines` branch the result is perfect! I did a double take because the two are really indistinguishable.

<img width="300" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/290205/a9d4d25f-34ce-43d9-a2fe-f946fbff95d9">

Some context: On Sept 12--14 our team will be presenting a 3 day tutorial on our [magnetism simulation package](https://sunnysuite.github.io/Sunny.jl/dev/examples/fei2_tutorial/) to 50 new Julia users at Oak Ridge National Lab. Workshop link: https://conference.sns.gov/event/383/. We will be presenting tutorials in Jupyter notebooks, and I'd really like to use WGLMakie because the "inline" notebook experience is so nice. If `sd/wgl-lines` were released by then, it would be amazing. But if not, is there a short term workaround to manually set the size of a WGLMakie display? (Changing the resolution doesn't work because it breaks, e.g., the font sizes.)

**Comment by jkrumbiegel** [comment]
Releasing 0.20 until then sounds like a tight timeline, don't think that's likely. For the size question, I'd have to punt that to @SimonDanisch. You can maybe force the canvas to be larger via css, but it will not be sharper.

**Comment by SimonDanisch** [comment]
I think the only way to do this will be to release 0.20 until then, since it's quite a bit of work with the correct font scaling etc... 
I think the 0.20 branch should be quite functional at this point, so one could think about shipping a manifest that checks out that branch, if it isn't released until then.
We can try to tag until then, but of course can't promise anything.

**Comment by kbarros** [comment]
Thanks for the update. The release shouldn't be rushed, and it also doesn't make sense to implement complicated font scaling logic, etc, that will be unneeded soon. I wonder if something like this could make it easier for people to get a beta version:

- Pkg uses SemVer, which supports prelease version numbers: https://semver.org/#spec-item-11, but the General registry does not support this.
- As a workaround, use [LocalRegistry](https://github.com/GunnarFarneback/LocalRegistry.jl) to create a Github repo that will be a local registry that contains some particular tagged beta, e.g. `Makie@0.20.0-beta.1` and similarly for `WGLMakie` and `GLMakie`.
- Potential beta testers would be asked to do something like this:
```
using Pkg
pkg"registry add <Github repo url>"
pkg"add Makie@0.20.0-beta.1"
pkg"add WGLMakie@...-beta.1"
```

This would make it easy for more people to test a potential `0.20` beta with minimal hassle, and avoiding the need to clone the entire Makie repo.

**Comment by SimonDanisch** [comment]
you can do this without a registry:
```
]add MakieCore#sd/beta-20 Makie#sd/beta-20 WGLMakie#sd/beta-20
```
Or do you mean that by cloning the entire repo? 
We could also release a tag without registering it, which could make this a bit nicer

**Comment by kbarros** [comment]
```
]add MakieCore#sd/beta-20 Makie#sd/beta-20 WGLMakie#sd/beta-20
```

This sounds like a very workable solution.

> Or do you mean that by cloning the entire repo?

Yes, I was suspecting `]add MakieCore#sd/beta-20 ...` would first need to clone the entire Makie repo, which takes some time and network bandwidth (we may have 50 people in a room executing this at the same time over Wifi). But given that your solution is a one-liner, it's very appealing.

> We could also release a tag without registering it

That would be great!

**Comment by staticfloat** [comment]
For the record, we also ship manifests to users with `]add MakieCore#sd/beta-20 Makie#sd/beta-20 WGLMakie#sd/beta-20`, and the improvements have been really helping!

One thing to note however is that the `Makie.jl` repository is _huge_ so if your users are downloading the package using `git` (which will happen in this case, since you're requesting a branch and not a tarball from a package server) the download time can be quite high; in my case it takes ~2 minutes to clone the Makie repository and that's from a server in a datacenter.  IMO it's still worth it to get these nice features, but if you get complaints about slow instantiation, this is why.

**Comment by staticfloat** [comment]
I think a custom registry with a "fake" version could work to solve this, but you'd most likely conflict with some future Makie version down the road, unfortunately.  You are correct in that you'd need to be downloading a registered version to get the "fast paths" in the Pkg downloading code (such as downloading a tarball from GitHub), which is a bit of a shame.

An alternative would be to fork the `Makie.jl` repository, copy over the `sd/beta-20` branch and then install from that repository instead of the main `MakieOrg/Makie.jl` repository.  That should speed up initial clones significantly.  I thought this was such a good idea, I did it on [my own fork](https://github.com/staticfloat/Makie.jl), so you can create a manifest with this for the time being:

```
Pkg.add(PackageSpec(;url="https://github.com/MakieOrg/Makie.jl", subdir="MakieCore", rev="sd/beta-20"))
Pkg.add(PackageSpec(;url="https://github.com/MakieOrg/Makie.jl", rev="sd/beta-20"))
Pkg.add(PackageSpec(;url="https://github.com/MakieOrg/Makie.jl", subdir="WGLMakie", rev="sd/beta-20"))
```

Substitute the final `WGLMakie` installation with whatever Makie backend you want.  I tested install time using:
```
JULIA_DEPOT_PATH=. time julia -e 'using Pkg; Pkg.add(PackageSpec(;url="https://github.com/MakieOrg/Makie.jl", subdir="MakieCore", rev="sd/beta-20"))'
```

There are a few confounding factors here (`juliaup` installation time, precompilation time, etc...) but the fact of the matter is that it reduces the total time from 194 seconds to 11 seconds, and that's at home with gigabit fiber.  So I think it should serve your workshop well.  I'd suggest making your own fork (and deleting all branches except for `master` and `sd/beta-20`) just in case I rebase my branch or something silly like that, causing troubles for your workshop.
