### ISSUE TITLE
Contour limits changed from `0.19.9` to `0.19.10`

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#3259]
@ffreyer I don't quite understand it yet but assume it's connected with https://github.com/MakieOrg/Makie.jl/pull/3227

MWE:

In 0.19.9, this contour plot has quite a lot of white space around it. Interestingly, the two different `data_limits` calls I `@show` have different return values. The latter is tighter. But I have already deleted the `text` child plot here which was introduced a while ago when labels were added.

```julia
using CairoMakie
using Makie.KernelDensity
using Random

Random.seed!(123)

x = randn(100)
y = randn(100)
k = kde(hcat(x, y))

f = Figure()
ax = Axis(f[1, 1])

c = contour!(ax, k.x, k.y, k.density)
popfirst!(c.plots)

@show Makie.data_limits(c)
@show Makie.data_limits(c.plots[1])

f
```

```
Makie.data_limits(c) = GeometryBasics.HyperRectangle{3, Float32}(Float32[-3.858967, -3.973673, 0.0], Float32[7.2212353, 8.19762, 0.0])
Makie.data_limits(c.plots[1]) = GeometryBasics.HyperRectangle{3, Float32}(Float32[-1.9766064, -1.5087711, 0.0], Float32[3.4296885, 3.5192566, 0.0])
```

This is the output image:

<img width="791" alt="image" src="https://github.com/MakieOrg/Makie.jl/assets/22495855/81edf1cf-8ec1-4e84-ad29-c2df6affe823">

When I define this method and don't delete the `text` plot

```julia
Makie.data_limits(c::Contour) = data_limits(c.plots[2])
```

I get this output plot:

![image](https://github.com/MakieOrg/Makie.jl/assets/22495855/1e486335-8197-402b-98de-d3e47812a54b)

Which corresponds to the tighter limits.

On 0.19.10 I get this output 

```
Makie.data_limits(c) = GeometryBasics.HyperRectangle{3, Float32}(Float32[-1.9766064, -1.5087711, 0.0], Float32[3.4296885, 3.5192566, 0.0])
Makie.data_limits(c.plots[1]) = GeometryBasics.HyperRectangle{3, Float32}(Float32[-1.9766064, -1.5087711, 0.0], Float32[3.4296885, 3.5192566, 0.0])
```

![image](https://github.com/MakieOrg/Makie.jl/assets/22495855/7f2bc8f8-438d-4a2e-bff5-e2564f6f3d30)

Maybe the new behavior is just a bug fix, and it seems so from the look of it because the limits are tighter around the actually visible lines. But I still want to understand why the old one had a different result, even when excluding the `text`.

**Comment by ffreyer** [comment]
There is still a `point_iterator` overwrite there which probably gets skipped now:
https://github.com/MakieOrg/Makie.jl/blob/2b8b8a1472f2fd8692a64a554f3b85669c297e90/src/basic_recipes/contours.jl#L326-L333

**Comment by ffreyer** [comment]
Yea, calling that reports the old results:
```julia
julia> Rect2f(Makie.point_iterator(c))
GeometryBasics.HyperRectangle{2, Float32}(Float32[-3.858967, -3.973673], Float32[7.2212353, 8.19762])
```
which should be the limits of the raw data input, rather than the generated lines.

I would say the new limits are better and we should just keep them. (Though they are probably a bit more expensive because there are probably more points in the lines than the input?)

**Comment by jkrumbiegel** [comment]
Yes I think they're better, too. Ok then I understand where the difference comes from. Still a bit weird that the result is different depending on whether a plot is nested or not, but maybe `data_limits` is not actually the correct entrypoint into this

**Comment by ffreyer** [comment]
> Yes I think they're better, too. Ok then I understand where the difference comes from. Still a bit weird that the result is different depending on whether a plot is nested or not, but maybe `data_limits` is not actually the correct entrypoint into this

The old path was `data_limits(parent_plot) -> point_iterator(parent_plot)` which uses the method I linked to above, i.e. it looks at the input data to figure out limits. Here you get different results from parent vs nested because you're looking at different data.

The new path is `data_limits(parent_plot) -> data_limits(child_plot) -> point_iterator(child_plot)` which grabs the limits from the processed data, the lines that are actually drawn (and the positions of labels). Without the text plot you get the same between the parent contour and the child lines plot. With text they might be a bit different, because the individual limits get composed.

I think this is one of those cases that could use some stronger definitions. What do we mean with `data_limits`? Is it related to the raw input data of a plot (old) or the data that gets visualized (new)? Given the context of plotting I'd say the latter.

**Comment by ffreyer** [comment]
Closing this as fixed
