### ISSUE TITLE
PolarAxis unable to set negative rlimits

### ISSUE THREAD

**Issue by mikeingold** [MakieOrg/Makie.jl#3375]
- [x] are you running newest version (version from docs) ?
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
```julia
julia> versioninfo()
Julia Version 1.9.4
Commit 8e5136fa29 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 32 × AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 16 on 32 virtual cores
Environment:
  JULIA_NUM_THREADS = 16
```

# Issue

It looks like **PolarAxis** does not support setting negative r limits or plotting lines with negative values. Polar plots are used frequently in electrical engineering to present things like antenna gain patterns, measured on a dB scale ([Example](https://www.mathworks.com/help/antenna/gs/antenna-modeling-and-analysis.html#AntennaModelingAndAnalysisTutorialExample-5)).

I demonstrated this with the MWE below, plotting a fake gain pattern in linear and dB scales on both a regular `Axis` and a `PolarAxis`. The polar plot in dB scale won't display any of the line because it's always <= 0. If I try to set `rlimits` to the appropriate range for this plot, e.g. `rlimits=(-40,0)` the r axis looks like a mess with no ticks remaining.

# Minimum Working Example

```julia
using CairoMakie

pow2db(x) = 20log10(x)

theta_prime = pi
angle(a,b) = min(abs(a-b), 2π-abs(a-b))
gain(theta) = abs(sinc(2.0*angle(theta,theta_prime)))

thetas = range(0, 2pi, length=361)
```

```julia
# Axis plots in linear and dB scale
f_xy = Figure()
ax_xy_lin = Axis(f_xy[1,1], title="Gain", xlabel="Theta [rad]")
lines!(ax_xy_lin, thetas, gain.(thetas))
ax_xy_dB = Axis(f_xy[1,2], title="Gain in dB", xlabel="Theta [rad]")
lines!(ax_xy_dB, thetas, pow2db.(gain.(thetas)))
save("f_xy.png", f_xy)
```

![f_xy](https://github.com/MakieOrg/Makie.jl/assets/4054970/840013b0-6b52-4339-9b96-28826b2f1440)

```julia
# PolarAxis plots in linear and dB scale
f_polar = Figure()
ax_polar_lin = PolarAxis(f_polar[1,1], title="Gain")
lines!(ax_polar_lin, thetas, gain.(thetas))
ax_polar_dB = PolarAxis(f_polar[1,2], title="Gain in dB")
lines!(ax_polar_dB, thetas, pow2db.(gain.(thetas)))
save("f_polar.png", f_polar)
```

![f_polar](https://github.com/MakieOrg/Makie.jl/assets/4054970/ad72f0d7-a6b7-462a-8e10-dac842d05b83)

**Comment by ffreyer** [comment]
We experimented with offsetting radii so that r_in > 0 ends up at r_out = 0 to increase the space a plot limited to a ring (sector) occupies. (I.e. with rmax > rmin >> 0.) That's what `radial_distortion_threshold` is about. With `r_out = r_in - r0` it sets a limit for how large `(r_min - r0) / (r_max - r0)` is allowed to get, calculating the r0.

Ultimately this won't help you, since it is restricted to r0 > 0. I also don't think you can hack this by setting r0 in `ax.scene.transformation.transform_func`, because of how the updates are set up and because PolarAxis probably assumes positive radii at times. 

But there is still some functionality for this in the background and I think replacing `radial_distortion_threshold` with directly setting r0 wouldn't be a bad idea. It seems easier to understand to me and more useful. 

If you want to try making these changes you could remove
https://github.com/MakieOrg/Makie.jl/blob/531d42d3c255f142bca171ff5d9faeb6903c72eb/src/makielayout/blocks/polaraxis.jl#L225-L230
and make `radius_at_origin` (the r0) an attribute of the PolarAxis by adding it here
https://github.com/MakieOrg/Makie.jl/blob/531d42d3c255f142bca171ff5d9faeb6903c72eb/src/makielayout/types.jl#L1690-L1696
The `radial_distortion_threshold` further above should be removed as well.
