### ISSUE TITLE
Scatter! does not render a section of the screen during animation

### ISSUE THREAD

**Issue by cdelv** [MakieOrg/Makie.jl#3524]
I was creating a program that simulates particle life to learn CUDA.jl. The program is attached to this issue. I noticed that when the number of particles exceeds roughly 2750, a section of the bottom left corner is not rendered. The particles are still there, they are just not drawn, which I think is weird. After reviewing the program, I concluded that this must be a Makie bug. Here are some pictures:

This one has 8k particles, notice the black spot.
![Makie_bug](https://github.com/MakieOrg/Makie.jl/assets/54986485/b1c1169f-40cb-46be-b0c4-9085d0413837)

This one has 2k particles, and the bug does not appear.
![Makie_bug](https://github.com/MakieOrg/Makie.jl/assets/54986485/aa2263d1-2b35-4bc7-97de-937ad05c2204)

- I'm using  GLMakie v0.9.4 and Julia 1.9.4
- I'm running Linux, specifically POP OS 22.04 LTS. My CPU: is AMD Ryzen 9 6900HS Creator Edition, and My GPU: is NVIDIA GeForce RTX 3050. The OS is instructed to use the integrated graphics in the AMD processor as the default GPU, which is the one Makie is using. 

I'm sorry I could not manage to create a more minimal working example, for some reason, this only happens during the animation. Other parameters like the window size or the amount of colors don't seem to affect much. 

Change the extension to .jl once you download the program. 
[main.txt](https://github.com/MakieOrg/Makie.jl/files/13796633/main.txt)

**Comment by SimonDanisch** [comment]
Your code is pretty complex and highly optimized with lots of `@inbounds` and uninitialized arrays etc. So unless you can reproduce this bug with a minimal working example that clearly points to Makie doing something wrong, I have to assume the problem is in your code ;) 
Feel free to re-open, once you have an MWE that clearly shows that GLMakie isn't rendering some points that should be there.
