### ISSUE TITLE
Fit objects into scene after Makie transformations

### ISSUE THREAD

**Issue by juliohm** [MakieOrg/Makie.jl#3562]
From a Discourse [thread](https://discourse.julialang.org/t/how-to-translate-and-scale-makie-image/108741), here is a MWE by @eliascarv where the image is partially displayed:

```julia
using Makie
using GLMakie

@recipe(ScaledImage, img, x, y) do scene
  Attributes()
end

function Makie.plot!(plot::ScaledImage)
  image!(plot, plot.img, interpolate=false)
  scale!(plot, plot.x[], plot.y[])
  # how to adjust the axis after scaling the plot?
end

img = rand(1:9, 10, 10)
scaledimage(img, 2.5, 1.5)
```
![image](https://github.com/MakieOrg/Makie.jl/assets/3345261/de946b95-ec9a-4620-bc2f-f87bf43f6c74)

**Comment by SimonDanisch** [comment]
I think, you could define your own `Makie.data_limits` as a work around for now! 
E.g. like this:
```julia
function Makie.data_limits(p::ScaledImage)
     edges = Point2f.(p[1][], p[2][]) # Get edges, pseudo code, needs to be 4 edges
     scaled_points = # scale the points
     return limits_from_transformed_points(scaled_points )
end
```

**Comment by asinghvi17** [comment]
`boundingbox(plot)` would be the best replacement.

**Comment by eliascarv** [comment]
Like this?
```julia
function Makie.data_limits(plot::ScaledImage)
     return boundingbox(plot)
end
```

**Comment by asinghvi17** [comment]
Most likely - but you may not need it at all in 0.21 with the changes to boundongbox computation

**Comment by ffreyer** [comment]
`data_limits(plot) = boundingbox(plot)` goes against what data_limits is supposed to do and it will break when transform functions are involved. I would also consider this an Axis bug now

**Comment by ffreyer** [comment]
Actually this isn't even an issue right now. We're including model in an incorrect way atm (which I thought would be the same as pre 0.21), so for the opening example I do get the correct scaling. What's missing is the tight spacing that you get from `Makie.needs_tight_limits(::ScaledImage) = true`, but that's expected.

Another issue you can run into atm is that the root plot's model matrix is considered here, not the ones of each children. so if you scale the image plot instead of the `ScaledImage` it won't work.
