### ISSUE TITLE
Broken fonts and plots with GLMakie after using PackageCompiler

### ISSUE THREAD

**Issue by icetube23** [MakieOrg/Makie.jl#3679]
I have encountered a strange (but most-likely already known) issue with GLMakie. I recently tried to use PackageCompiler.jl to compile a Julia app (using the `create_app` function) completely unrelated to Makie/GLMakie. After that I started having issues with GLMakie rendering like these:

```julia
julia> scatter([0])
```
<img src="https://github.com/MakieOrg/Makie.jl/assets/34234056/b010b10a-946c-44b7-9b7f-122f4c259e69" width="400" />

```julia
julia> lines((1:20) .+ randn(20))
```
<img src="https://github.com/MakieOrg/Makie.jl/assets/34234056/444c43b1-796b-456c-8664-36de7713a333" width="400" />

I'm running on the latest Makie and Julia versions (Makie v0.20.8, GLMakie v0.9.9, Julia 1.10.2) and the problem also occurs in fresh environments. My platform is a Ubuntu 20.04 running in WSL2 with a NVIDIA Quadro P2200 gpu. The problem does not occur with CairoMakie.

Visually my problem seems to be related to some old already closed issues (#1854, #2480, #2521). #2521 combined with the fact that I experimented with PackageCompiler directly before the problem started occuring, lead me to believe that this might have something to do with it. It is really strange to me because all these old issues are already solved and the app I tried to compile had nothing to do with Makie at all.

However, after trying out various fixes for hours, I've simply ran out of ideas on what I could still try. What I already tried:
- Downgrading the versions of Makie, GLMakie and Julia
- Reinstalling GLMakie
- Deleting the `makie` folders in `.julia` and `.julia/scratchspaces/<uuid>`
- Reinstalling OS font packages in `/etc/fonts`
- Wiping and reinstalling julia (i.e., `rm -rf ~/.julia`)

So far, none of those worked. The fact that not even reinstalling julia fixes the problem suggests that this is most-likely not a bug in GLMakie. Maybe I accidently broke or corrupted some files on my system that are used by GLMakie?

Thanks in advance for any pointers or advice on what I could still try :)

**Comment by SimonDanisch** [comment]
This does not seem to be related to the texture atlas or the fonts, so I guess removing all those folders wont change anything.
I think there must be something seriously wrong with the GPU driver, since its not just the fonts but lines and scatter also rendering incorrectly, which doesn't depend on anything like fonts/textureatlas etc. Its a bit weird though, that it doesn't just error / segfault, like it's usually the case with broken drivers - and instead just renders incorrectly. It looks like it just completely skips any operation in the fragment shader.

> Ubuntu 20.04 running in WSL2 with a NVIDIA Quadro P2200 gpu

I expect that something broke here, we've seen quite a few WSL2 issues, the drivers seem to be more brittle than linux/windows drivers alone.
Mesa could also be a culprit. I'd try upgrading all related software (windows, wsl2, nvidia driver, linux, mesa etc)

**Comment by icetube23** [comment]
Thanks a lot for your suggestions! You were spot on, it really was a problem with Mesa.

To make GLMakie precompile successfully in WSL, I initially had to add the [kisak-mesa ppa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) to my system. This ppa recently updated its Mesa packages to version 24.0.2 (before I was on version 23.3.5). After installing these updates, GLMakie broke for me. I managed to fix the problem by purging the kisak-mesa ppa from my system and replacing it with the more stable (but less supported) [turtle ppa](https://launchpad.net/~kisak/+archive/ubuntu/turtle/). Simply downgrading kisak-mesa might also work.

Afterall, my problem really was unrelated to GLMakie (and PackageCompiler). Sorry for the noise!
