### ISSUE TITLE
`heatmap` gives `nan_color` to cell not in data

### ISSUE THREAD

**Issue by pfuchter** [MakieOrg/Makie.jl#3782]
MWE:
```
x = [1,2,3,1,2,3,1,3,1,2,3]
y = [1,1,1,2,2,2,3,3,4,4,4]
z = [1,NaN,3,4,5,6,7,8,9,10,11]
heatmap(x,y,z,nan_color=:black)
```
![image](https://github.com/MakieOrg/Makie.jl/assets/93337642/26037a51-a2fa-4157-a041-193e722a10d5)

- [x] are you running newest version (version from docs) ?
--GLMakie v0.9.10
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on?
--windows + nvidia mx250

**Comment by jkrumbiegel** [comment]
Hm as the heatmap is fundamentally matrix shaped and the vector syntax is just for giving one in long format, and we use NaN for missingness in a bunch of places (because that's traditional in plotting software) I think that behavior makes sense. Gaps are just transparent cells, you cannot have real gaps with heatmap. If you need that, plot your cells as a vector of rects with `poly`

**Comment by pfuchter** [comment]
Fair enough, makes sense!

My actual use case prompted me to make the post, in which points not included in `x,y,z` are not included because they show no behaviour, whereas NaN points show behaviour but it is not possible to define z. I guess I was surprised by the behaviour as in my mind NaN is different to missing. 

I just had another look at the heatmap docs and realised I can include the missing data and use lowclip/highclip to set the colour to white. If that doesn't work I'll use the poly suggestion, cheers!

**Comment by jkrumbiegel** [comment]
Nice, was about to suggest clipping but you already got to it. Will close this then :)
