### ISSUE TITLE
Wrong units

### ISSUE THREAD

**Issue by jariji** [MakieOrg/Makie.jl#4063]
```jl
  [13f3f980] CairoMakie v0.12.5
  [1986cc42] Unitful v1.21.0


julia> scatter(rand(5)u"m/s", rand(5)u"m/s")
```

The units are wrong.

![image](https://github.com/user-attachments/assets/d6995101-c4e3-4025-861e-c3cd0d0e8d1e)

**Comment by SimonDanisch** [comment]
Why it switches to decimeter is because the default is to automatically switch to the best unit.
Why it drops the second is not really clear to me...
You could have a look at: https://github.com/MakieOrg/Makie.jl/blob/master/src/dim-converts/unitful-integration.jl
And see where it goes wrong!

**Comment by ffreyer** [comment]
It's one of the base_unit() calls. 
https://github.com/MakieOrg/Makie.jl/blob/4c4eaa1f3a7f7b3777a4b8ab38388a48c0eee6ce/src/dim-converts/unitful-integration.jl#L14-L16
It goes through these 3 in order where in the last one `U = (m, s^-1)`, so that indexing just grabs `m`

**Comment by ffreyer** [comment]
It looks like most of this is for adjusting unit prefixes to the range of numbers given. E.g. changing `10000m .. 54000m` to `10km .. 54km`. I wonder if we should just drop those conversions. 
It seems difficult to apply them to compound units - e.g. if you have "A * B / C", should A, B or C get a prefix? Some people may also supply specific prefixes on purpose because they are commonly used (e.g. g/cm^3). It also looks like this is not generic atm, i.e. we'd have to define valid prefixes for every unit and add special cases to avoid things like `dft` (deci-feet).

**Comment by jariji** [comment]
Yeah keeping the user's units seems good.

**Comment by abhro** [comment]
Is there an option to do it at the top (or right) of the axes? I mean in the style that MATLAB does power of 10 representations (linear plot, scaled), then putting the units on top of the axis might help (see first image of <https://tutorial45.com/matlab-plot-colors-and-styles/>)

**Comment by nathanrboyer** [comment]
There are no circumstances under which I want to plot deka-feet. 😑
Is there a quick switch to get `ft` back, and can `d`, `c`, `da`, and `h` be excluded from the automatic conversions?

![Image](https://github.com/user-attachments/assets/bd18990f-2856-4b2c-9e16-022ea29c3a55)

**Comment by ffreyer** [comment]
You can turn off automatic conversions if you create the conversion manually. It's explained in `?Makie.UnitfulConversion`

**Comment by nathanrboyer** [comment]
Okay, thanks. I got that working. I still think conversions from 10^-2 through 10^2 should be automatically avoided though.
