### ISSUE TITLE
Should we publish a paper?

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/Makie.jl#428]
A conversation with @kescobo on Slack got me thinking that we should publish a Makie paper!  

[Journal of Open Source Software](https://joss.readthedocs.io/en/latest) looks like a good place to publish, but if anyone has a better idea please let me know!

There are guidelines on that website about writing a paper.

@Datseris, I think you also published some papers about DynamicalSystems there?  Would love if you could share your experience / any tips.

If anyone has any other suggestions / opinions, please let us know!

**Comment by Datseris** [comment]
Hi, yeah I've published 3 papers there and I am also a reviewer in the journal. You can ask for me to review if you submit. The process varies vastly depending on who you get as a reviewer and who you get as an editor. With some combinations its smooth sailing, with some others you have to deal with stupid things.

It is certainly not a scientific review process, as at least in my scenario, the reviewers I got had 0 scientific comments about actually improving my software or paper. E.g. algorithms, design, etc. 

What I would certainly ask for, if I was a reviewer, is how this software compares to other existing software that do the same things. For example, is the total amount of functionality on par, greater or inferior? The performance? Etc. These things should be discussed in the paper, as well as what novelty the software brings to the table (which I guess with Makie is easy to do because of the `Observables` integration). 

Just so you know, I am a brutal reviewer and will cut no slack if you ask for me :P 

---

My advice, if I may, would be to try and bring a more professional look to the default settings of Makie before submitting the paper. You can see how much different it is from other well established packages that are used for publication quality figures. For example if I just saw this: https://simondanisch.github.io/ReferenceImages/gallery/barplot_1/index.html and so how PyPLot does a histogram, it is clear for me what I should use for my scientific papers. (this may be an extreme example, but I don't know why there are ridiculusly long tick lines, almost 25% of the entire plot)

But besides this point, I Think you should definitely write a paper about makie. The performance and interactivity alone should be enough to get it through.

**Comment by asinghvi17** [comment]
Thanks for the feedback!  Yeah, this is definitely a long term prospect, probably after we integrate MakieLayout, after which axes will look way nicer.  This is a plot that Kevin made using MakieLayout, for instance:
<img width="1077" alt="Screen Shot 2020-01-24 at 6 01 30 PM" src="https://user-images.githubusercontent.com/32143268/73123188-3d39e680-3f5b-11ea-9ab6-243808e1dbce.png">

**Comment by Datseris** [comment]
Oh YEAH this is what I am tacking about! Hooooly hell this looks nice.

**Comment by kescobo** [comment]
😄 you must include @jkrumbiegel though - the underlying data is mine, but most of the effort to make it look nice was from his package and unwavering willingness to answer my questions

**Comment by mkborregaard** [comment]
It's a good idea but totally up to @simondanisch i guess

**Comment by mkborregaard** [comment]
In fact I'd think for JOSS it would be possible with a small suite of papers:
- a MakieLayout paper, based on e.g. that figure, led by @jkrumbiegel, illustrating links and boxes and the underlying design idea
- a Makie paper led by @SimonDanisch , could focus e.g. on the plotting on the GPU, the interface with backends, the first-order-citizen interactions by Observables
- a StatsMakie paper led by @piever focusing on a fresh take on the GOG
- a GeoMakie paper led by @asinghvi17 perhaps once that's ready?

and maybe a few more once the functionality is there - maybe next year?

**Comment by SimonDanisch** [comment]
This seems like a good topic for Vizcon :) It'd be amazing to have this, but also, I don't want to commit to even more work I don't really have time for :D

**Comment by kescobo** [comment]
@SimonDanisch Totally understandable, but given how much work you've put in already, I don't think it would be unreasonable for others to write the paper(s) with your input (and have you still get the bulk of credit w/r/t author position etc if that's a thing for JOSS papers)

**Comment by SimonDanisch** [comment]
I think @Kevin-Mattheus-Moerman also proposed this. Kevin, do you think its feasible to do this?

**Comment by mkborregaard** [comment]
It definitely is. I'm the software-paper editor for one of big ecology journals, and these papers are the kind of thing you want to publish - presenting a really worked-through software package with a novel approach to an old problem.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi all, I'm an AEiC at JOSS and also a fan of Makie.jl. Yes in principle Makie.jl is a good candidate for JOSS. We have published visualization packages before but they require a research application. So as long as you clearly describe the impact Makie.jl is having/has had on science then it sounds like this could be a great submission. 

@SimonDanisch formulating a JOSS paper probably does not take you a lot of time. It would be a nice way for you and the contributors involved to get academic credit for this important work. 

Let me know if you have more questions. 

Thanks @Datseris for your comments about JOSS (and thanks for being a helpful reviewer in the past!): 
> It is certainly not a scientific review process, as at least in my scenario, the reviewers I got had 0 scientific comments about actually improving my software or paper. E.g. algorithms, design, etc.

That is disappointing. Sad to hear you felt that the review was not very scientific at times. If you want to formulate specific feedback about particular review issues please let me know. We have been updating/improving our review criteria and editorial process a lot over time. We tend to act rapidly on suggested improvements so if you have any thoughts let us know. (In fact there is a call for new editors now so if you want to help improve JOSS by joining the team let us know @Datseris) 

> What I would certainly ask for, if I was a reviewer, is how this software compares to other existing software that do the same things. 

This is now formulated clearly in our review criteria and literally relates to a checkbox in the review issue. So if reviewers have ignored this it should have been flagged. 

> For example, is the total amount of functionality on par, greater or inferior? The performance? Etc. These things should be discussed in the paper, as well as what novelty the software brings to the table (which I guess with Makie is easy to do because of the Observables integration).

Comparison to other works is also specifically asked for. I recently updated our criteria and the reviewer checklist about what should be discussed in relation to this in the paper. So hopefully what you experienced will be reduced in the future. 
You are right that some reviewers are more thorough than others. It is up to the editors to spot this but it can be difficult. The authors are probably also in a good spot to comment on the quality of the review process during review. I do feel that at the moment JOSS probably offers the most scientific review of software, i.e. our criteria actually demand the software is tested and functionality is checked. In other journals this is not the case, a "paper only" review is not sufficient.

**Comment by mkborregaard** [comment]
@Kevin-Mattheus-Moerman what's your take on the multi-paper model I suggested above? I think there's enough independent functionality to merit that, and would make for clearer submissions - so it's not a case of salami-slicing imho.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mkborregaard I just saw your comments there. If those separate papers cover quite separate functionality and we can easily imagine that one would feel the need to separately cite them, then perhaps this is justified. 

I think it would be good for other editors to chime in on this too. Perhaps you could post a pre-submission enquiry issue here, where you can make your case: 
https://github.com/openjournals/joss/issues

**Comment by asinghvi17** [comment]
Could someone in the thread be so kind as to write up a pre=submission enquiry?  I unfortunately don't have the bandwidth right now :(

**Comment by mkborregaard** [comment]
Let's talk about this at the Vizcon

**Comment by jkrumbiegel** [comment]
I wanted to revive this issue, because it could be helpful in the long term to allow people using Makie in their scientific work to cite it properly. Currently, we only have a zenodo identifier with an absurd list of collaborators (even tagbot was in there last I checked).

In my opinion, it's fair if Simon is first author and I'm second, while everybody who contributed bug fixes, smaller features, etc. can be named in the acknowledgements. I'd be interested to hear how others feel about this. My reasoning being that Simon is obviously the creator, so first author, and I have contributed a big chunk which is the now default plotting interface and layout system. Those are the two big conceptual pieces of work in this package, so I'd limit the authors to us two. It seems that others are following that approach as well. For example, consider this https://joss.theoj.org/papers/10.21105/joss.03021 Seaborn paper with one author, and the corresponding contributor graph:

<img width="919" alt="grafik" src="https://user-images.githubusercontent.com/22495855/113901847-8d534080-97cf-11eb-9f9d-c539d719bc1f.png">

Our AbstractPlotting graph currently looks like this, which I think is a similar picture:

<img width="916" alt="grafik" src="https://user-images.githubusercontent.com/22495855/113901949-a6f48800-97cf-11eb-92e4-1273c121dc1b.png">

I'd be willing to write the paper up as well and make the required examples etc., so there's no work involved for anybody else here. But it's important to me to do this transparently and if necessary discuss the authorship further, if there are objections against limiting it to "Danisch & Krumbiegel (2021)".

**Comment by kescobo** [comment]
That makes a lot of sense to me. Looks like the next person with any claim would be @asinghvi17 (who also started this thread). I think @piever should do a separate paper on AlgebraOfGraphics.jl

**Comment by piever** [comment]
I also think that it makes sense to have as authors the core devs.

I agree with @kescobo that AlgebraOfGraphics should probably be a separate paper that would cite the first: it really is two separate stories IMO.

**Comment by jkrumbiegel** [comment]
@ffreyer good point, I should have checked the backends separately.

**Comment by jkrumbiegel** [comment]
I've written a paper at https://github.com/JuliaPlots/AbstractPlotting.jl/blob/joss-paper/paper.md and would like to get the review process rolling. The JOSS site asks me to specify a reviewer and the two that I recognize are @Kevin-Mattheus-Moerman and @dpsanders. I'd appreciate any suggestions as to who I should pick from either of you, if that's possible. Thanks for your help!
