### ISSUE TITLE
regression: plot recipes that take kwargs don't work anymore

### ISSUE THREAD

**Issue by aplavin** [MakieOrg/Makie.jl#4351]
The new patch release breaks recipes that take kwargs, I guess mostly applicable to recipes returning SpecApi.
MWE that creates a nice red line in v0.21.9 but errors in v0.21.10:
```julia
julia> using Makie
julia> import Makie.SpecApi as S
julia> struct MyS end
julia> Makie.convert_arguments(::Type{Lines}, ::MyS; kwargs...) = S.Lines([1,2,3], [1,2,3]; kwargs...)
julia> Makie.used_attributes(T::Type{<:Plot}, ::MyS) = (Makie.attribute_names(T)...,)
julia> lines(MyS(); color=:red)
```
The error:
```
ERROR: MethodError: no method matching transform!(::Transformation, ::Nothing)

Closest candidates are:
  transform!(::MakieCore.Transformable, ::Tuple{Symbol, Number})
   @ Makie ~/.julia/packages/Makie/WgbrE/src/layouting/transformation.jl:169
  transform!(::MakieCore.Transformable, ::Union{Attributes, AbstractDict, NamedTuple})
   @ Makie ~/.julia/packages/Makie/WgbrE/src/layouting/transformation.jl:70
  transform!(::MakieCore.Transformable; translation, scale, rotation)
   @ Makie ~/.julia/packages/Makie/WgbrE/src/layouting/transformation.jl:59

Stacktrace:
 [1] connect_plot!(parent::Scene, plot::Plot{Makie.plotlist, Tuple{PlotSpec}})
   @ Makie ~/.julia/packages/Makie/WgbrE/src/interfaces.jl:383
 [2] plot!
   @ ~/.julia/packages/Makie/WgbrE/src/interfaces.jl:409 [inlined]
 [3] plot!(ax::Axis, plot::Plot{Makie.plotlist, Tuple{PlotSpec}})
   @ Makie ~/.julia/packages/Makie/WgbrE/src/figureplotting.jl:412
 [4] plot!(fa::Makie.FigureAxis, plot::Plot{Makie.plotlist, Tuple{PlotSpec}})
   @ Makie ~/.julia/packages/Makie/WgbrE/src/figureplotting.jl:407
 [5] _create_plot(F::Function, attributes::Dict{Symbol, Any}, args::MyS)
   @ Makie ~/.julia/packages/Makie/WgbrE/src/figureplotting.jl:318
 [6] #lines#60
   @ ~/.julia/packages/MakieCore/k9SbO/src/recipes.jl:449 [inlined]
 [7] lines(args::MyS)
   @ MakieCore ~/.julia/packages/MakieCore/k9SbO/src/recipes.jl:447
 [8] top-level scope
   @ REPL[6]:1
```
- [x] what version of Makie are you running? (`]st -m Makie`) v0.21.10
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
- [x] What platform + GPU are you on? any

**Comment by SimonDanisch** [comment]
Hm, so you shouldn't really do that - and the patch release fixes exactly the issue, why you probably had to forward all attributes to convert_arguments.
You should be able to do this now:
```julia
using GLMakie
import Makie.SpecApi as S
struct MyS end

function Makie.convert_arguments(::Type{Lines}, ::MyS)
    S.Lines([1, 2, 3], [1, 2, 3])
end
lines(MyS(); color=:red)
```
To be fair, I'm not 100% sure why it returns nothing for transformation and e.g. space - but that's something that you shouldn't forward to `convert_arguments` anyways.

**Comment by SimonDanisch** [comment]
Yeah sorry about that, it's not tested, and the consequence of this was also unexpected... 
Btw, in the docs, the SpecApi is still declared as experimental, with expected breakage even in patch releases, exactly because of this, since it's still not tested  well enough and hard to see what we will accidentally break in a patch release.

It seems like you're depending quite a bit on more internal/experimental Makie features, the best way to make sure they don't get broken unexpectedly would be to add more tests to Makie, covering your use cases ;)

**Comment by SimonDanisch** [comment]
It only gets applied to a single PlotSpec ;) Indeed this may need to get documented somewhere ...

**Comment by asinghvi17** [comment]
Should we expand that to at least set the theme for lists of plotspecs, blockspecs, etc?

**Comment by asinghvi17** [comment]
Yes, one can try some combination of `Makie.shared_attributes` plus `Makie.used_attributes(plottype, argtypes...)` to select keys for each plotspec, I think!

**Comment by asinghvi17** [comment]
In the plotlist recipe, one could simply pass `merge(Makie.shared_attributes(PlotType, plotlist_plot_object), plotlist_attrs)` or something when actually plotting the plotlist.  The code there is a bit complicated though, since it tries to diff through the existing plots in the plotlist to avoid creating new plots whenever possible.
