### ISSUE TITLE
Scatter `marker_offset` is broken

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/Makie.jl#4383]
I get this in CairoMakie and GLMakie with Makie v0.21.11, the dots should be separated.

```julia
scatter([1, 1, 1], [1, 1, 1], marker_offset = [(10, 10), (0, 20), (-15, -15)])
```

<img width="595" alt="image" src="https://github.com/user-attachments/assets/f82f423f-572c-4dfa-9020-18a6dc4b1599">

**Comment by CaptainKubi** [comment]
I am having the same issue. 
I tried downgrading my Makie and CairoMakie version. 
I stopped at v0.18.0 for Makie and 0.9.0 for CairoMakie and it still did not work on my system.

**Comment by ffreyer** [comment]
It's ignored in this function, but adding it here will be incompatible with defaults for char markers. 
https://github.com/MakieOrg/Makie.jl/blob/da86824d2ffa44818f490018382875fe594a9899/src/utilities/texture_atlas.jl#L512

We should probably split up the marker centering offset from the user adjustable offset. The backend infrastructure for that should mostly already be there, since text has two offsets like that. For GLMakie that would be `quad_offset` for centering and `marker_offset` (char_offset in text) for the user attribute
