### ISSUE TITLE
Julia Registry is missing WGLMakie 0.10.15

### ISSUE THREAD

**Issue by EdsterG** [MakieOrg/Makie.jl#4537]
Need to finish merging https://github.com/JuliaRegistries/General/pull/118119. Maybe fixed by https://github.com/MakieOrg/Makie.jl/pull/4532?

**Comment by SimonDanisch** [comment]
I'm not sure why the compat entry isn't accepted, but the reason why introduced it was because of: https://github.com/JuliaWeb/HTTP.jl/issues/1189
Since it _looks_ like something that can be fixed quickly, i'd just wait for a new HTTP.jl release and then just remove the compat entry for LoggingExtras in WGLMakie.

**Comment by EdsterG** [comment]
@SimonDanisch I don’t think this issue is resolved yet. The registrar needs to be retriggered to release WGLMakie 0.10.15

**Comment by SimonDanisch** [comment]
Yeah I know, was just a bit slow with it...

**Comment by EdsterG** [comment]
Yay, it's merged. Thank you!
