### ISSUE TITLE
Inset axis can affect the placement of parent figure

### ISSUE THREAD

**Issue by daviehh** [MakieOrg/Makie.jl#4637]
- [x] what version of Makie are you running? (`]st -m Makie`)
  > [ee78f7c6] Makie v0.21.16
- [x] can you reproduce the bug with a fresh environment ? (`]activate --temp; add Makie`)
  > yes
- [x] What platform + GPU are you on?
  > macos, m1 (happens on CairoMakie makie too so not gpu-dependent)

A main figure with y axis on the left, with inset:
- inset y axis on the right, Makie would think the main figure's y axis is on the right too and adds a blank space to the right (upper panel)
- inset yaxis on the left, no issue (lower panel)

mwe:
```julia
using CairoMakie

x = 0:0.01:7

let
    fig = Figure(backgroundcolor=(:orange, 0.3))
    ax = Makie.Axis(fig[1, 1])
    lines!(x, exp.(x) .* sin.(x))

    inset_ax = Makie.Axis(fig[1, 1],
        width=Relative(0.5),
        height=Relative(0.4),
        halign=0.1,
        valign=0.9,
        yaxisposition=:right,
        backgroundcolor=:white)

    hidexdecorations!(inset_ax, ticks=false, ticklabels=false)
    hideydecorations!(inset_ax, ticks=false, ticklabels=false)

    lines!(x, cos.(x))

    save("makie_bug_a.png", fig)
    fig
end

let
    fig = Figure(backgroundcolor=(:orange, 0.3))
    ax = Makie.Axis(fig[1, 1])
    lines!(x, exp.(x) .* sin.(x))

    inset_ax = Makie.Axis(fig[1, 1],
        width=Relative(0.5),
        height=Relative(0.4),
        halign=0.3,
        valign=0.9,
        # yaxisposition=:right,
        backgroundcolor=:white)

    hidexdecorations!(inset_ax, ticks=false, ticklabels=false)
    hideydecorations!(inset_ax, ticks=false, ticklabels=false)

    lines!(x, cos.(x))

    save("makie_bug_b.png", fig)
    fig
end

```

![Image](https://github.com/user-attachments/assets/2067e075-5511-49df-b0d7-d80916da9e65)

**Comment by jkrumbiegel** [comment]
This is not a bug, but a limitation of the layout algorithm. When you place the inset axis in layout cell 1,1, its protrusions are incorporated into the layout cell's overall protrusions even if you reduce the size via `width = Relative(0.5)` etc. That's because the width resulting from `Relative(0.5)` can only be computed after knowing the protrusions.

The simplest option here is to give the inset axis `alignmode = Outside()` which means the protrusions are counted as the "inner" part of the axis, so the actual protrusions are zero by default:

```julia
using CairoMakie

x = 0:0.01:7

fig = Figure(backgroundcolor=(:orange, 0.3))
ax = Makie.Axis(fig[1, 1])
lines!(x, exp.(x) .* sin.(x))

inset_ax = Makie.Axis(fig[1, 1],
    width=Relative(0.5),
    height=Relative(0.4),
    halign=0.1,
    valign=0.9,
    yaxisposition=:right,
    backgroundcolor=:white,
    alignmode = Outside()
)

hidexdecorations!(inset_ax, ticks=false, ticklabels=false)
hideydecorations!(inset_ax, ticks=false, ticklabels=false)

lines!(x, cos.(x))

fig
```

![Image](https://github.com/user-attachments/assets/16a461d8-6353-42b5-a0aa-2ec107ee01ba)
