### ISSUE TITLE
Scaling of 3D plots

### ISSUE THREAD

**Issue by grahamas** [MakieOrg/Makie.jl#590]
Nearly every 3D plot I make initially looks really buggy because of scaling issues. Usually, it doesn't even look like a plot at first. Consider `sc = surface(1.0:0.01:2.0, 100.0:200.0, rand(10,10))`.

While I can see several reasons for this to be default behavior, it's liable to cause confusion. The first time I saw it, I thought it was a glitch, and wasted a while thinking there was some weird rendering issue. Worse, it's inconsistent with 2D plots, which do autoscale.

I think it's worth discussing changing the default behavior if you haven't already. But at the least, I think this is a common enough problem that 1) it deserves a convenience function, and 2) the surface example in the Makie gallery should showcase this problem.  I'm happy to make a PR if that path is what seems best.  As far as I can tell, the convenience function is super simple:

```
function auto_scale!(sc::Scene)
    raw_scales = 1 ./ scene_limits(sc).widths
    scaling = raw_scales ./ minimum(raw_scales)
    scale!(sc, scaling)
end
```

**Comment by asinghvi17** [comment]
I would probably go one further, and suggest the following:

```julia
function box_widths!(sc::Scene, aspects::NTuple{3, Float32} = (1f0, 1f0, 1f0))
    raw_scales = 1 ./ widths(scene_limits(sc))
    scaling = raw_scales ./ minimum(raw_scales) .* aspects
    scale!(sc, scaling)
end
```


I'll test this out later today, and PR it to AbstractPlotting.  We will probably only really "solve" this during the MakieLayout integration, though.

**Comment by asinghvi17** [comment]
@SimonDanisch should we add this as a hook in the `plot!` pipeline, and pick up `scale_plot` in 3D plots?

**Comment by asinghvi17** [comment]
Just tested this, and can confirm it works.

```julia
scene = surface(AbstractPlotting.peaks(100))
```
<img width="832" alt="Screen Shot 2020-05-03 at 10 05 51  86300AM" src="https://user-images.githubusercontent.com/32143268/80898836-0297d500-8d26-11ea-9119-f14c878d910f.png">
```julia
box_widths!(scene)
```
<img width="832" alt="Screen Shot 2020-05-03 at 10 06 02  07700AM" src="https://user-images.githubusercontent.com/32143268/80898844-19d6c280-8d26-11ea-8f17-7babdd0f224c.png">
```julia
box_widths!(scene, (1f0, 2f0, 1f0))
center!(scene)
```
<img width="832" alt="Screen Shot 2020-05-03 at 10 07 21  25300AM" src="https://user-images.githubusercontent.com/32143268/80898846-24915780-8d26-11ea-89d4-fed38f84354d.png">

The only issue is that the axis label sizes become too small, since they are in dataspace (and no longer account for the Scene's transformation).

**Comment by ffreyer** [comment]
You can use `Axis3` to auto-scale 3D plots now.
