### ISSUE TITLE
Per face colors ?

### ISSUE THREAD

**Issue by j-fu** [MakieOrg/Makie.jl#705]
Hi, is it possible to support per face colors for Meshes in AbstractPlotting.poly ?

Jürgen

**Comment by ffreyer** [comment]
On a fundamental/backend level no, because OpenGL and WebGL don't have a `face_index` to work with. Instead you have to duplicate vertices (positions, normals, colors) so that each face has a unique set of vertices with a unique color. Offering some convenience function for this would be possible, but that might also be something for https://github.com/JuliaGeometry/GeometryBasics.jl/pull/173

**Comment by ffreyer** [comment]
Closing this in favor of #1369 since there is more discussion there
