### ISSUE TITLE
Bad default in xticks!

### ISSUE THREAD

**Issue by knuesel** [MakieOrg/Makie.jl#773]
The convenience functions `xticks!`, `yticks!` and `zticks!` have signatures like:

```
xticks!([scene,]; xtickrange=xtickrange(scene), xticklabels=xticklabels(scene))
```

The default value for `xticklabels` doesn't seem right: It will do the wrong thing in the common case where the user just wants to change the range:

```julia
julia> s = scatter(1:10, resolution=(300,200))

julia> xticks!(s, xtickrange=1:10)
```

![image](https://user-images.githubusercontent.com/2412819/101056944-ccf0ee00-358b-11eb-8a43-3639b1bd5784.png)

Here I would expect the same result as

```julia
julia> xticks!(s, xtickrange=1:10, xticklabels=["$x" for x in 1:10])
```

![image](https://user-images.githubusercontent.com/2412819/101057337-396bed00-358c-11eb-80d7-8c3165a515ef.png)

**Comment by knuesel** [comment]
A backward-compatible fix would be to deprecate the keywords `xtickrange` and `xticklabels` which are needlessly verbose and define something like:

```
xticks!([scene,]; range=xtickrange(scene), labels=nothing)
```

**Comment by yha** [comment]
I'm not sure having `xtickslabels` as a separate kwarg is a good idea, since one should always set labels together with tick locations, usually as a function of the tick values. I think the `Plots.jl` interface here is better: you can pass a function in `xformatter` that maps tick value to tick label, or pass a tuple `xticks=(values, labels)`.
Also, `xtickrange` accepts non-ranges as well, so it should probably not have "range" in its name.

**Comment by ffreyer** [comment]
Closing this as outdated/fixed since we have `Axis` now
