### ISSUE TITLE
CairoMakie backend does not produce arrow plot correctly

### ISSUE THREAD

**Issue by danielchen26** [MakieOrg/Makie.jl#860]
```
using CairoMakie
CairoMakie.activate!(type = "svg")

xs = LinRange(-1, 4, 20)
ys = LinRange(-1, 4, 20)
f1(x,y) =  5/(1 + y^2) -x
f2(x,y) =  5/(1 + x^2) -y
u = [f1(x,y) for x in xs, y in ys]
v = [f2(x,y) for x in xs, y in ys]
arrows(xs, ys, u, v, arrowsize = 0.5, lengthscale = 0.05, resolution = (2800, 2200))
```
GLMakie does the job correctly, but with low resolution. The Cairo backend does have better quality but without arrow plotted.
<img width="531" alt="Screen Shot 2021-02-28 at 4 44 23 PM" src="https://user-images.githubusercontent.com/5272189/109434632-385c2780-79e4-11eb-9047-431ade0ee188.png">

**Comment by elkaps** [comment]
Setting `arrowsize=10` seems to produce the correct image:
![test](https://user-images.githubusercontent.com/44770441/111903397-66acb000-8a42-11eb-81be-cedd9cbcce52.png)

**Comment by jkrumbiegel** [comment]
the problem here is that the original arrow recipe used markers in data space, which means their rotation correctly adapted to axis scaling, but at the same time the arrow tips could also be skewed like still visible in the docs:

![grafik](https://user-images.githubusercontent.com/22495855/111904970-ae830580-8a49-11eb-9968-f6414bf3376a.png)

Additionally, the size of the arrows was also set in data coordinates, which CairoMakie wasn't written to use. CairoMakie expectes markers in screen coordinates size, so 10 gives 10px markers. On the other hand, the rotation of the CairoMakie markers is interpreted as screen rotation, which is wrong because the axis scaling should affect the rotation as well. So basically, we need to fix it so the markers are rotated so that the final visual rotation is correct, given the current axis projection

**Comment by ffreyer** [comment]
Closing this since CairoMakie and GLMakie have the same behavior now
