### ISSUE TITLE
AbstractPlotting document `current_figure` and `current_axis`

### ISSUE THREAD

**Issue by nandoconde** [MakieOrg/Makie.jl#901]
Currently (😆), the only documented `current_X` function is `current_scene`.

Given the scene-to-figure refactoring that took place, I think it makes much more sense that the user has access to a succint description of what these method do, as they are used a lot in an interactive way with Makie.

I have opened a [PR in AbstractPlotting](https://github.com/JuliaPlots/AbstractPlotting.jl/pull/682) with very short version of these based on the docstring of `current_scene`, feel free to change it.

**Comment by jkrumbiegel** [comment]
ah yeah would be good to solidify this a bit. I've thought about having shorter versions though, a bit like matlab with `gcf()` for get current figure, because the main use is interactively and it's annoying to type. Maybe `ca()` and `ca!()` for axis and `cf()` and `cf!()` for figure. What do you think @SimonDanisch

**Comment by ffreyer** [comment]
Closing this since docstrings exist now
